/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as Oid4vciRouteImport } from './routes/oid4vci'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContentComponentIdRouteImport } from './routes/content/$componentId'
import { Route as AccountSecuritySigningInRouteImport } from './routes/account-security/signing-in'
import { Route as AccountSecurityLinkedAccountsRouteImport } from './routes/account-security/linked-accounts'
import { Route as AccountSecurityDeviceActivityRouteImport } from './routes/account-security/device-activity'

const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const Oid4vciRoute = Oid4vciRouteImport.update({
  id: '/oid4vci',
  path: '/oid4vci',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentComponentIdRoute = ContentComponentIdRouteImport.update({
  id: '/content/$componentId',
  path: '/content/$componentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSecuritySigningInRoute =
  AccountSecuritySigningInRouteImport.update({
    id: '/account-security/signing-in',
    path: '/account-security/signing-in',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountSecurityLinkedAccountsRoute =
  AccountSecurityLinkedAccountsRouteImport.update({
    id: '/account-security/linked-accounts',
    path: '/account-security/linked-accounts',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountSecurityDeviceActivityRoute =
  AccountSecurityDeviceActivityRouteImport.update({
    id: '/account-security/device-activity',
    path: '/account-security/device-activity',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/groups': typeof GroupsRoute
  '/oid4vci': typeof Oid4vciRoute
  '/organizations': typeof OrganizationsRoute
  '/resources': typeof ResourcesRoute
  '/account-security/device-activity': typeof AccountSecurityDeviceActivityRoute
  '/account-security/linked-accounts': typeof AccountSecurityLinkedAccountsRoute
  '/account-security/signing-in': typeof AccountSecuritySigningInRoute
  '/content/$componentId': typeof ContentComponentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/groups': typeof GroupsRoute
  '/oid4vci': typeof Oid4vciRoute
  '/organizations': typeof OrganizationsRoute
  '/resources': typeof ResourcesRoute
  '/account-security/device-activity': typeof AccountSecurityDeviceActivityRoute
  '/account-security/linked-accounts': typeof AccountSecurityLinkedAccountsRoute
  '/account-security/signing-in': typeof AccountSecuritySigningInRoute
  '/content/$componentId': typeof ContentComponentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/groups': typeof GroupsRoute
  '/oid4vci': typeof Oid4vciRoute
  '/organizations': typeof OrganizationsRoute
  '/resources': typeof ResourcesRoute
  '/account-security/device-activity': typeof AccountSecurityDeviceActivityRoute
  '/account-security/linked-accounts': typeof AccountSecurityLinkedAccountsRoute
  '/account-security/signing-in': typeof AccountSecuritySigningInRoute
  '/content/$componentId': typeof ContentComponentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/groups'
    | '/oid4vci'
    | '/organizations'
    | '/resources'
    | '/account-security/device-activity'
    | '/account-security/linked-accounts'
    | '/account-security/signing-in'
    | '/content/$componentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/groups'
    | '/oid4vci'
    | '/organizations'
    | '/resources'
    | '/account-security/device-activity'
    | '/account-security/linked-accounts'
    | '/account-security/signing-in'
    | '/content/$componentId'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/groups'
    | '/oid4vci'
    | '/organizations'
    | '/resources'
    | '/account-security/device-activity'
    | '/account-security/linked-accounts'
    | '/account-security/signing-in'
    | '/content/$componentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  GroupsRoute: typeof GroupsRoute
  Oid4vciRoute: typeof Oid4vciRoute
  OrganizationsRoute: typeof OrganizationsRoute
  ResourcesRoute: typeof ResourcesRoute
  AccountSecurityDeviceActivityRoute: typeof AccountSecurityDeviceActivityRoute
  AccountSecurityLinkedAccountsRoute: typeof AccountSecurityLinkedAccountsRoute
  AccountSecuritySigningInRoute: typeof AccountSecuritySigningInRoute
  ContentComponentIdRoute: typeof ContentComponentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oid4vci': {
      id: '/oid4vci'
      path: '/oid4vci'
      fullPath: '/oid4vci'
      preLoaderRoute: typeof Oid4vciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$componentId': {
      id: '/content/$componentId'
      path: '/content/$componentId'
      fullPath: '/content/$componentId'
      preLoaderRoute: typeof ContentComponentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-security/signing-in': {
      id: '/account-security/signing-in'
      path: '/account-security/signing-in'
      fullPath: '/account-security/signing-in'
      preLoaderRoute: typeof AccountSecuritySigningInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-security/linked-accounts': {
      id: '/account-security/linked-accounts'
      path: '/account-security/linked-accounts'
      fullPath: '/account-security/linked-accounts'
      preLoaderRoute: typeof AccountSecurityLinkedAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-security/device-activity': {
      id: '/account-security/device-activity'
      path: '/account-security/device-activity'
      fullPath: '/account-security/device-activity'
      preLoaderRoute: typeof AccountSecurityDeviceActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  GroupsRoute: GroupsRoute,
  Oid4vciRoute: Oid4vciRoute,
  OrganizationsRoute: OrganizationsRoute,
  ResourcesRoute: ResourcesRoute,
  AccountSecurityDeviceActivityRoute: AccountSecurityDeviceActivityRoute,
  AccountSecurityLinkedAccountsRoute: AccountSecurityLinkedAccountsRoute,
  AccountSecuritySigningInRoute: AccountSecuritySigningInRoute,
  ContentComponentIdRoute: ContentComponentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
