import { IEnvironment } from '@novu/shared';
import { apiHostnameManager } from '@/utils/api-hostname-manager';
import { getToken } from '@/utils/auth';
import {
  fakeActivity,
  fakeAgents,
  fakeApiKeys,
  fakeChartData,
  fakeEnvironments,
  fakeEnvVars,
  fakeIntegrations,
  fakeLayouts,
  fakeOrg,
  fakeSubscribers,
  fakeTags,
  fakeTopics,
  fakeUser,
  fakeWorkflows,
  pickActivity,
  pickAgent,
  pickIntegration,
  pickLayout,
  pickSubscriber,
  pickTopic,
  pickWorkflow,
} from './fake-data';
// This is how we import the speakeasy autogenerated Novu SDK that is CJS in a the Dashboard ESM project with Vite
// Read more at https://github.com/vitejs/vite/issues/5668#issuecomment-968117934

/** DO NOT CHANGE THIS CODE START */
// import * as NovuAPI from '@novu/api';

// const { Novu } = NovuAPI;

// export const novuClient = new Novu();
/** DO NOT CHANGE THIS CODE END */

export class NovuApiError extends Error {
  constructor(
    public message: string,
    public status: number,
    public rawError?: unknown
  ) {
    super(message);
  }
}

type HttpMethod = 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';

// Offline mode: the dashboard runs without any Novu backend. Every API call
// is short-circuited to canned realistic data from ./fake-data.
function pathParts(endpoint: string): string[] {
  const [path] = endpoint.split('?');
  return (path ?? '').split('/').filter(Boolean);
}

function offlineFallback(endpoint: string): unknown {
  const parts = pathParts(endpoint);
  const [root, sub, ...rest] = parts;

  switch (root) {
    case 'environments':
      if (!sub) return { data: fakeEnvironments };
      if (sub === 'api-keys') return { data: fakeApiKeys };
      if (rest[0] === 'tags') return { data: { tags: fakeTags } };
      if (rest[0] === 'diff') return { data: { changes: [] } };
      if (rest[0] === 'publish') return { data: { changes: [] } };
      return { data: fakeEnvironments[0] };

    case 'organizations':
      return { data: fakeOrg };

    case 'users':
      return { data: fakeUser };

    case 'workflows': {
      if (!sub) return { data: { workflows: fakeWorkflows, totalCount: fakeWorkflows.length } };
      const wf = pickWorkflow(sub);
      if (rest[0] === 'test-data') {
        return { data: { schema: { type: 'object', properties: {} }, payload: {} } };
      }
      return { data: wf };
    }

    case 'layouts': {
      if (!sub) return { data: { layouts: fakeLayouts, totalCount: fakeLayouts.length } };
      const lay = pickLayout(sub);
      if (rest[0] === 'usage') return { data: { workflows: [] } };
      if (rest[0] === 'preview') {
        return { data: { result: { preview: { body: '<p>Preview</p>', subject: 'Preview' } } } };
      }
      return { data: lay };
    }

    case 'integrations': {
      if (!sub) return { data: fakeIntegrations };
      if (rest[0] === 'set-primary') return { data: pickIntegration(sub) };
      if (rest[0] === 'auto-configure') return { data: { success: true } };
      if (rest[0] === 'msteams-arm-template') return { data: { deployUrl: '#' } };
      if (rest[0] === 'msteams-azure-setup') return { data: { url: '#' } };
      if (rest[0] === 'msteams-health') return { data: { healthy: true } };
      return { data: pickIntegration(sub) };
    }

    case 'subscribers': {
      if (!sub) {
        return {
          data: fakeSubscribers,
          totalCount: fakeSubscribers.length,
          page: 0,
          pageSize: 10,
          hasMore: false,
        };
      }
      const subscriber = pickSubscriber(sub);
      if (rest[0] === 'preferences') {
        return {
          data: {
            global: { enabled: true, channels: {} },
            workflows: fakeWorkflows.map((w) => ({
              workflow: { _id: w._id, name: w.name, identifier: w.workflowId },
              preference: { enabled: true, channels: {} },
            })),
          },
        };
      }
      if (rest[0] === 'subscriptions') {
        return { data: [], totalCount: 0, page: 0, pageSize: 10, hasMore: false };
      }
      return { data: subscriber };
    }

    case 'notifications': {
      if (!sub) {
        return {
          data: fakeActivity,
          totalCount: fakeActivity.length,
          page: 0,
          pageSize: 10,
          hasMore: false,
        };
      }
      return { data: pickActivity(sub) };
    }

    case 'activity': {
      if (sub === 'workflow-runs') {
        if (rest[0]) return { data: { ...pickActivity(rest[0]), steps: [] } };
        return {
          data: fakeActivity.map((a) => ({ ...a, workflowName: a.template.name })),
          totalCount: fakeActivity.length,
          page: 0,
          pageSize: 10,
          hasMore: false,
        };
      }
      if (sub === 'charts') return { data: fakeChartData };
      if (sub === 'requests') {
        if (rest[0]) return { data: { traces: [] } };
        return { data: [], totalCount: 0, page: 0, pageSize: 10, hasMore: false };
      }
      return { data: [], totalCount: 0, page: 0, pageSize: 10, hasMore: false };
    }

    case 'topics': {
      if (!sub) {
        return { data: fakeTopics, totalCount: fakeTopics.length, page: 0, pageSize: 10 };
      }
      const topic = pickTopic(sub);
      if (rest[0] === 'subscriptions') {
        if (rest[1]) return { data: { subscriber: fakeSubscribers[0], topic } };
        return { data: [], totalCount: 0, page: 0, pageSize: 10, hasMore: false };
      }
      return { data: topic };
    }

    case 'environment-variables': {
      if (!sub) return { data: fakeEnvVars };
      if (rest[0] === 'usage') return { data: { workflows: [] } };
      return { data: fakeEnvVars[0] };
    }

    case 'agents': {
      if (!sub) return { data: fakeAgents, totalCount: fakeAgents.length };
      if (sub === 'emoji') return { data: ['🤖', '💼', '⚡', '🎯', '🚀', '🛟'].map((e) => ({ emoji: e })) };
      const agent = pickAgent(sub);
      if (rest[0] === 'integrations') {
        return { data: [], totalCount: 0, page: 0, pageSize: 10 };
      }
      if (rest[0] === 'welcome-message') return { data: { message: `Hello, I'm ${agent.name}` } };
      if (rest[0] === 'test-email') return { success: true };
      return { data: agent };
    }

    case 'step-resolvers':
      if (sub === 'count') return { data: { count: 0 } };
      return { data: [] };

    case 'bridge':
      if (sub === 'status') return { data: { status: 'ok', sdkVersion: '0.0.0', frameworkVersion: '0.0.0' } };
      if (sub === 'validate') return { data: { isValid: true } };
      return { data: {} };

    case 'domains': {
      if (!sub) return { data: [], next: null };
      if (rest[0] === 'routes') return { data: [], next: null };
      if (rest[0] === 'auto-configure') return { data: { status: 'not-configured' } };
      return { data: { name: sub, status: 'verified', records: [] } };
    }

    case 'translations': {
      if (sub === 'list') {
        return { data: [], totalCount: 0, page: 0, pageSize: 10, hasMore: false };
      }
      if (sub === 'master-json') return { data: { translations: {} } };
      return { data: { translations: {}, resources: [] } };
    }

    case 'ai': {
      if (sub === 'workflow-suggestions') {
        if (rest[0] === 'onboarding') return { data: { suggestions: [] } };
        return { data: [] };
      }
      if (sub === 'chat') return { data: { message: '', threadId: 'fake-thread' } };
      return { data: { success: true } };
    }

    case 'contexts': {
      if (!sub) return { data: [], totalCount: 0, page: 0, pageSize: 10, hasMore: false };
      return { data: { type: sub, items: [] } };
    }

    case 'outbound-webhooks':
      return { data: { token: 'fake-portal-token', url: '#' } };

    case 'partner-integrations':
      return { data: { success: true } };

    case 'conversations': {
      if (!sub) return { data: [], totalCount: 0, page: 0, pageSize: 10, hasMore: false };
      if (rest[0] === 'activities') {
        return { data: [], totalCount: 0, page: 0, pageSize: 10, hasMore: false };
      }
      return { data: { _id: sub, messages: [] } };
    }

    case 'feature-flags':
    case 'inbox':
    case 'telemetry':
      return { data: {} };

    case 'events':
      return { data: { transactionId: 'fake-tx' } };

    default:
      return { data: [] };
  }
}

const request = async <T>(
  endpoint: string,
  options?: {
    environment?: IEnvironment;
    body?: unknown;
    method?: HttpMethod;
    headers?: HeadersInit;
    version?: 'v1' | 'v2';
    signal?: AbortSignal;
  }
): Promise<T> => {
  const { body, environment, headers, method = 'GET', version = 'v1', signal } = options || {};

  // Offline / mock mode: never hit the network. Return canned fake data
  // shaped like Novu's API responses so the dashboard renders end-to-end.
  return offlineFallback(endpoint) as T;

  // eslint-disable-next-line no-unreachable
  try {
    const jwt = await getToken();
    const config: RequestInit = {
      method,
      headers: {
        Authorization: `Bearer ${jwt}`,
        'Content-Type': 'application/json',
        ...(environment && { 'Novu-Environment-Id': environment._id }),
        ...headers,
      },
      signal,
    };

    if (body) {
      if (body instanceof FormData) {
        // For FormData, don't stringify and don't set Content-Type (let browser handle it)
        config.body = body;
        // Remove Content-Type header for FormData
        delete (config.headers as Record<string, string>)['Content-Type'];
      } else {
        config.body = JSON.stringify(body);
      }
    }

    const baseUrl = apiHostnameManager.getHostname();
    const response = await fetch(`${baseUrl}/${version}${endpoint}`, config);

    if (!response.ok) {
      const errorData = await response.json();
      throw new NovuApiError(parseErrorMessage(errorData), response.status, errorData);
    }

    if (response.status === 204) {
      return {} as T;
    }

    return await response.json();
  } catch (error) {
    if (error instanceof NovuApiError) {
      throw error;
    }

    // Offline mode: backend unreachable (CORS / connection refused / TypeError).
    // Return a safe payload so the UI renders instead of crashing.
    const isNetworkError =
      error instanceof TypeError ||
      (typeof error === "object" && error && "message" in error &&
        typeof (error as { message: unknown }).message === "string" &&
        /Failed to fetch|NetworkError|Load failed/i.test(
          (error as { message: string }).message,
        ));
    if (isNetworkError) {
      return offlineFallback(endpoint) as T;
    }

    if (typeof error === 'object' && error && 'message' in error) {
      throw new Error(`Fetch error: ${error.message}`);
    }

    throw new Error(`Fetch error: ${JSON.stringify(error)}`);
  }
};

type RequestOptions = { body?: unknown; environment?: IEnvironment; signal?: AbortSignal; headers?: HeadersInit };

export const get = <T>(endpoint: string, { environment, signal, headers }: RequestOptions = {}) =>
  request<T>(endpoint, { method: 'GET', environment, signal, headers });
export const post = <T>(endpoint: string, options: RequestOptions) =>
  request<T>(endpoint, { method: 'POST', ...options });
export const put = <T>(endpoint: string, options: RequestOptions) =>
  request<T>(endpoint, { method: 'PUT', ...options });
export const del = <T>(endpoint: string, { environment, signal }: RequestOptions = {}) =>
  request<T>(endpoint, { method: 'DELETE', environment, signal });
export const patch = <T>(endpoint: string, options: RequestOptions) =>
  request<T>(endpoint, { method: 'PATCH', ...options });

export const getV2 = <T>(endpoint: string, { environment, signal }: RequestOptions = {}) =>
  request<T>(endpoint, { version: 'v2', method: 'GET', environment, signal });
export const postV2 = <T>(endpoint: string, options: RequestOptions) =>
  request<T>(endpoint, { version: 'v2', method: 'POST', ...options });
export const putV2 = <T>(endpoint: string, options: RequestOptions) =>
  request<T>(endpoint, { version: 'v2', method: 'PUT', ...options });
export const delV2 = <T>(endpoint: string, options: RequestOptions) =>
  request<T>(endpoint, { version: 'v2', method: 'DELETE', ...options });
export const patchV2 = <T>(endpoint: string, options: RequestOptions) =>
  request<T>(endpoint, { version: 'v2', method: 'PATCH', ...options });

function parseErrorMessage(errorData: any): string {
  const DEFAULT_ERROR = 'Novu API error';

  if (!errorData?.message) {
    return DEFAULT_ERROR;
  }

  if (Array.isArray(errorData.message)) {
    return errorData.message.filter(Boolean).join('. ') || DEFAULT_ERROR;
  }

  if (typeof errorData.message !== 'string') {
    return errorData.message?.message || DEFAULT_ERROR;
  }

  try {
    const parsedMessage = JSON.parse(errorData.message);

    return parsedMessage.message || DEFAULT_ERROR;
  } catch {
    return errorData.message?.message || errorData.message || DEFAULT_ERROR;
  }
}

export function getApiBaseUrl(): string {
  return apiHostnameManager.getHostname();
}
