/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3"
import { safeParse } from "../../lib/schemas.js"
import type { Result as SafeParseResult } from "../../types/fp.js"
import type { SDKValidationError } from "../errors/sdkvalidationerror.js"
import {
  type CreatedSubscriberDto,
  CreatedSubscriberDto$inboundSchema,
} from "./createdsubscriberdto.js"
import {
  type FailedOperationDto,
  FailedOperationDto$inboundSchema,
} from "./failedoperationdto.js"
import {
  type UpdatedSubscriberDto,
  UpdatedSubscriberDto$inboundSchema,
} from "./updatedsubscriberdto.js"

export type BulkCreateSubscriberResponseDto = {
  /**
   * An array of subscribers that were successfully updated.
   */
  updated: Array<UpdatedSubscriberDto>
  /**
   * An array of subscribers that were successfully created.
   */
  created: Array<CreatedSubscriberDto>
  /**
   * An array of failed operations with error messages and optional subscriber IDs.
   */
  failed: Array<FailedOperationDto>
}

/** @internal */
export const BulkCreateSubscriberResponseDto$inboundSchema: z.ZodType<
  BulkCreateSubscriberResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  updated: z.array(UpdatedSubscriberDto$inboundSchema),
  created: z.array(CreatedSubscriberDto$inboundSchema),
  failed: z.array(FailedOperationDto$inboundSchema),
})

export function bulkCreateSubscriberResponseDtoFromJSON(
  jsonString: string
): SafeParseResult<BulkCreateSubscriberResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BulkCreateSubscriberResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BulkCreateSubscriberResponseDto' from JSON`
  )
}
