/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3"
import { safeParse } from "../../lib/schemas.js"
import type { Result as SafeParseResult } from "../../types/fp.js"
import type { SDKValidationError } from "../errors/sdkvalidationerror.js"
import { type MetaDto, MetaDto$inboundSchema } from "./metadto.js"
import {
  type SubscriptionDto,
  SubscriptionDto$inboundSchema,
} from "./subscriptiondto.js"
import {
  type SubscriptionsDeleteErrorDto,
  SubscriptionsDeleteErrorDto$inboundSchema,
} from "./subscriptionsdeleteerrordto.js"

export type DeleteTopicSubscriptionsResponseDto = {
  /**
   * The list of successfully deleted subscriptions
   */
  data: Array<SubscriptionDto>
  /**
   * Metadata about the operation
   */
  meta: MetaDto
  /**
   * The list of errors for failed deletion attempts
   */
  errors?: Array<SubscriptionsDeleteErrorDto> | undefined
}

/** @internal */
export const DeleteTopicSubscriptionsResponseDto$inboundSchema: z.ZodType<
  DeleteTopicSubscriptionsResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(SubscriptionDto$inboundSchema),
  meta: MetaDto$inboundSchema,
  errors: z.array(SubscriptionsDeleteErrorDto$inboundSchema).optional(),
})

export function deleteTopicSubscriptionsResponseDtoFromJSON(
  jsonString: string
): SafeParseResult<DeleteTopicSubscriptionsResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteTopicSubscriptionsResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteTopicSubscriptionsResponseDto' from JSON`
  )
}
