/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3"
import { safeParse } from "../../lib/schemas.js"
import type { Result as SafeParseResult } from "../../types/fp.js"
import type { SDKValidationError } from "../errors/sdkvalidationerror.js"
import {
  type TextAlignEnum,
  TextAlignEnum$inboundSchema,
} from "./textalignenum.js"

export type EmailBlockStyles = {
  /**
   * Text alignment for the email block
   */
  textAlign: TextAlignEnum
}

/** @internal */
export const EmailBlockStyles$inboundSchema: z.ZodType<
  EmailBlockStyles,
  z.ZodTypeDef,
  unknown
> = z.object({
  textAlign: TextAlignEnum$inboundSchema,
})

export function emailBlockStylesFromJSON(
  jsonString: string
): SafeParseResult<EmailBlockStyles, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmailBlockStyles$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmailBlockStyles' from JSON`
  )
}
