/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3"
import { safeParse } from "../../lib/schemas.js"
import type { Result as SafeParseResult } from "../../types/fp.js"
import type { SDKValidationError } from "../errors/sdkvalidationerror.js"
import {
  type EmailControlsDto,
  EmailControlsDto$inboundSchema,
} from "./emailcontrolsdto.js"

export type LayoutControlValuesDto = {
  /**
   * Email layout controls
   */
  email?: EmailControlsDto | undefined
}

/** @internal */
export const LayoutControlValuesDto$inboundSchema: z.ZodType<
  LayoutControlValuesDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  email: EmailControlsDto$inboundSchema.optional(),
})

export function layoutControlValuesDtoFromJSON(
  jsonString: string
): SafeParseResult<LayoutControlValuesDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LayoutControlValuesDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LayoutControlValuesDto' from JSON`
  )
}
