/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3"
import { safeParse } from "../../lib/schemas.js"
import type { Result as SafeParseResult } from "../../types/fp.js"
import type { SDKValidationError } from "../errors/sdkvalidationerror.js"
import {
  type SubscriberPreferenceChannels,
  SubscriberPreferenceChannels$inboundSchema,
} from "./subscriberpreferencechannels.js"
import {
  type SubscriberPreferenceOverrideDto,
  SubscriberPreferenceOverrideDto$inboundSchema,
} from "./subscriberpreferenceoverridedto.js"
import {
  type SubscriberPreferencesWorkflowInfoDto,
  SubscriberPreferencesWorkflowInfoDto$inboundSchema,
} from "./subscriberpreferencesworkflowinfodto.js"

export type SubscriberWorkflowPreferenceDto = {
  /**
   * Whether notifications are enabled for this workflow
   */
  enabled: boolean
  /**
   * Channel-specific preference settings for this workflow
   */
  channels: SubscriberPreferenceChannels
  /**
   * List of preference overrides
   */
  overrides: Array<SubscriberPreferenceOverrideDto>
  /**
   * Workflow information
   */
  workflow: SubscriberPreferencesWorkflowInfoDto
  /**
   * Timestamp when the subscriber last updated their preference. Only present if subscriber explicitly set preferences.
   */
  updatedAt?: string | undefined
}

/** @internal */
export const SubscriberWorkflowPreferenceDto$inboundSchema: z.ZodType<
  SubscriberWorkflowPreferenceDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  enabled: z.boolean(),
  channels: SubscriberPreferenceChannels$inboundSchema,
  overrides: z.array(SubscriberPreferenceOverrideDto$inboundSchema),
  workflow: SubscriberPreferencesWorkflowInfoDto$inboundSchema,
  updatedAt: z.string().optional(),
})

export function subscriberWorkflowPreferenceDtoFromJSON(
  jsonString: string
): SafeParseResult<SubscriberWorkflowPreferenceDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SubscriberWorkflowPreferenceDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubscriberWorkflowPreferenceDto' from JSON`
  )
}
