packages:
  - "apps/*"
  - "apps/server/*"
  - "apps/notification/dashboard"
  - "apps/notification/libs/*"
  - "apps/notification/packages/*"
  - "apps/notification/enterprise/workers/*"
  - "packages/*"
  - "!apps/notification"
