/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { activityTrack } from "../funcs/activityTrack.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type ActivityTrackMutationVariables = {
  request: operations.InboundWebhooksControllerHandleWebhookRequest
  options?: RequestOptions
}

export type ActivityTrackMutationData = Array<components.WebhookResultDto>

export type ActivityTrackMutationError =
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Track provider activity and engagement events
 *
 * @remarks
 * Track activity and engagement events for a specific delivery provider
 */
export function useActivityTrackMutation(
  options?: MutationHookOptions<
    ActivityTrackMutationData,
    ActivityTrackMutationError,
    ActivityTrackMutationVariables
  >
): UseMutationResult<
  ActivityTrackMutationData,
  ActivityTrackMutationError,
  ActivityTrackMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildActivityTrackMutation(client, options),
    ...options,
  })
}

export function mutationKeyActivityTrack(): MutationKey {
  return ["@novu/api", "Activity", "track"]
}

export function buildActivityTrackMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: ActivityTrackMutationVariables
  ) => Promise<ActivityTrackMutationData>
} {
  return {
    mutationKey: mutationKeyActivityTrack(),
    mutationFn: function activityTrackMutationFn({
      request,
      options,
    }): Promise<ActivityTrackMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(activityTrack(client$, request, mergedOptions))
    },
  }
}
