/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { cancel } from "../funcs/cancel.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type CancelMutationVariables = {
  transactionId: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type CancelMutationData = operations.EventsControllerCancelResponse

export type CancelMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Cancel triggered event
 *
 * @remarks
 *
 *     Using a previously generated transactionId during the event trigger,
 *      will cancel any active or pending workflows. This is useful to cancel active digests, delays etc...
 */
export function useCancelMutation(
  options?: MutationHookOptions<
    CancelMutationData,
    CancelMutationError,
    CancelMutationVariables
  >
): UseMutationResult<
  CancelMutationData,
  CancelMutationError,
  CancelMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildCancelMutation(client, options),
    ...options,
  })
}

export function mutationKeyCancel(): MutationKey {
  return ["@novu/api", "cancel"]
}

export function buildCancelMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: CancelMutationVariables
  ) => Promise<CancelMutationData>
} {
  return {
    mutationKey: mutationKeyCancel(),
    mutationFn: function cancelMutationFn({
      transactionId,
      idempotencyKey,
      options,
    }): Promise<CancelMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        cancel(client$, transactionId, idempotencyKey, mergedOptions)
      )
    },
  }
}
