/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { channelEndpointsUpdate } from "../funcs/channelEndpointsUpdate.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type ChannelEndpointsUpdateMutationVariables = {
  updateChannelEndpointRequestDto: components.UpdateChannelEndpointRequestDto
  identifier: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type ChannelEndpointsUpdateMutationData =
  operations.ChannelEndpointsControllerUpdateChannelEndpointResponse

export type ChannelEndpointsUpdateMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Update a channel endpoint
 *
 * @remarks
 * Update an existing channel endpoint by its unique identifier.
 */
export function useChannelEndpointsUpdateMutation(
  options?: MutationHookOptions<
    ChannelEndpointsUpdateMutationData,
    ChannelEndpointsUpdateMutationError,
    ChannelEndpointsUpdateMutationVariables
  >
): UseMutationResult<
  ChannelEndpointsUpdateMutationData,
  ChannelEndpointsUpdateMutationError,
  ChannelEndpointsUpdateMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildChannelEndpointsUpdateMutation(client, options),
    ...options,
  })
}

export function mutationKeyChannelEndpointsUpdate(): MutationKey {
  return ["@novu/api", "Channel Endpoints", "update"]
}

export function buildChannelEndpointsUpdateMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: ChannelEndpointsUpdateMutationVariables
  ) => Promise<ChannelEndpointsUpdateMutationData>
} {
  return {
    mutationKey: mutationKeyChannelEndpointsUpdate(),
    mutationFn: function channelEndpointsUpdateMutationFn({
      updateChannelEndpointRequestDto,
      identifier,
      idempotencyKey,
      options,
    }): Promise<ChannelEndpointsUpdateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        channelEndpointsUpdate(
          client$,
          updateChannelEndpointRequestDto,
          identifier,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
