/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { channelEndpointsCreate } from "../funcs/channelEndpointsCreate.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type ChannelEndpointsCreateMutationVariables = {
  requestBody: operations.ChannelEndpointsControllerCreateChannelEndpointRequestBody
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type ChannelEndpointsCreateMutationData =
  operations.ChannelEndpointsControllerCreateChannelEndpointResponse

export type ChannelEndpointsCreateMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Create a channel endpoint
 *
 * @remarks
 * Create a new channel endpoint for a resource.
 */
export function useChannelEndpointsCreateMutation(
  options?: MutationHookOptions<
    ChannelEndpointsCreateMutationData,
    ChannelEndpointsCreateMutationError,
    ChannelEndpointsCreateMutationVariables
  >
): UseMutationResult<
  ChannelEndpointsCreateMutationData,
  ChannelEndpointsCreateMutationError,
  ChannelEndpointsCreateMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildChannelEndpointsCreateMutation(client, options),
    ...options,
  })
}

export function mutationKeyChannelEndpointsCreate(): MutationKey {
  return ["@novu/api", "Channel Endpoints", "create"]
}

export function buildChannelEndpointsCreateMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: ChannelEndpointsCreateMutationVariables
  ) => Promise<ChannelEndpointsCreateMutationData>
} {
  return {
    mutationKey: mutationKeyChannelEndpointsCreate(),
    mutationFn: function channelEndpointsCreateMutationFn({
      requestBody,
      idempotencyKey,
      options,
    }): Promise<ChannelEndpointsCreateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        channelEndpointsCreate(
          client$,
          requestBody,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
