/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { contextsUpdate } from "../funcs/contextsUpdate.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type ContextsUpdateMutationVariables = {
  request: operations.ContextsControllerUpdateContextRequest
  options?: RequestOptions
}

export type ContextsUpdateMutationData =
  operations.ContextsControllerUpdateContextResponse

export type ContextsUpdateMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Update a context
 *
 * @remarks
 * Update the data of an existing context.
 *       **type** and **id** are required fields, **data** is required. Only the data field is updated, the rest of the context is not affected.
 *       If the context does not exist, it returns the 404 response
 */
export function useContextsUpdateMutation(
  options?: MutationHookOptions<
    ContextsUpdateMutationData,
    ContextsUpdateMutationError,
    ContextsUpdateMutationVariables
  >
): UseMutationResult<
  ContextsUpdateMutationData,
  ContextsUpdateMutationError,
  ContextsUpdateMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildContextsUpdateMutation(client, options),
    ...options,
  })
}

export function mutationKeyContextsUpdate(): MutationKey {
  return ["@novu/api", "Contexts", "update"]
}

export function buildContextsUpdateMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: ContextsUpdateMutationVariables
  ) => Promise<ContextsUpdateMutationData>
} {
  return {
    mutationKey: mutationKeyContextsUpdate(),
    mutationFn: function contextsUpdateMutationFn({
      request,
      options,
    }): Promise<ContextsUpdateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(contextsUpdate(client$, request, mergedOptions))
    },
  }
}
