/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { contextsDelete } from "../funcs/contextsDelete.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type ContextsDeleteMutationVariables = {
  type: string
  id: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type ContextsDeleteMutationData =
  | operations.ContextsControllerDeleteContextResponse
  | undefined

export type ContextsDeleteMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Delete a context
 *
 * @remarks
 * Delete a context by its type and id.
 *       **type** and **id** are required fields, if the context does not exist, it returns the 404 response
 */
export function useContextsDeleteMutation(
  options?: MutationHookOptions<
    ContextsDeleteMutationData,
    ContextsDeleteMutationError,
    ContextsDeleteMutationVariables
  >
): UseMutationResult<
  ContextsDeleteMutationData,
  ContextsDeleteMutationError,
  ContextsDeleteMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildContextsDeleteMutation(client, options),
    ...options,
  })
}

export function mutationKeyContextsDelete(): MutationKey {
  return ["@novu/api", "Contexts", "delete"]
}

export function buildContextsDeleteMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: ContextsDeleteMutationVariables
  ) => Promise<ContextsDeleteMutationData>
} {
  return {
    mutationKey: mutationKeyContextsDelete(),
    mutationFn: function contextsDeleteMutationFn({
      type,
      id,
      idempotencyKey,
      options,
    }): Promise<ContextsDeleteMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        contextsDelete(client$, type, id, idempotencyKey, mergedOptions)
      )
    },
  }
}
