/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { domainsAutoConfigureStart } from "../funcs/domainsAutoConfigureStart.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type DomainsAutoConfigureStartMutationVariables = {
  createDomainConnectApplyUrlDto: components.CreateDomainConnectApplyUrlDto
  domain: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type DomainsAutoConfigureStartMutationData =
  operations.DomainsControllerStartDomainAutoConfigureResponse

export type DomainsAutoConfigureStartMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Start DNS auto-configuration
 *
 * @remarks
 * Generates a signed redirect URL the customer can follow to apply Novu DNS records at their DNS provider. After the provider completes the flow, it redirects back to `redirectUri`.
 */
export function useDomainsAutoConfigureStartMutation(
  options?: MutationHookOptions<
    DomainsAutoConfigureStartMutationData,
    DomainsAutoConfigureStartMutationError,
    DomainsAutoConfigureStartMutationVariables
  >
): UseMutationResult<
  DomainsAutoConfigureStartMutationData,
  DomainsAutoConfigureStartMutationError,
  DomainsAutoConfigureStartMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildDomainsAutoConfigureStartMutation(client, options),
    ...options,
  })
}

export function mutationKeyDomainsAutoConfigureStart(): MutationKey {
  return ["@novu/api", "AutoConfigure", "start"]
}

export function buildDomainsAutoConfigureStartMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: DomainsAutoConfigureStartMutationVariables
  ) => Promise<DomainsAutoConfigureStartMutationData>
} {
  return {
    mutationKey: mutationKeyDomainsAutoConfigureStart(),
    mutationFn: function domainsAutoConfigureStartMutationFn({
      createDomainConnectApplyUrlDto,
      domain,
      idempotencyKey,
      options,
    }): Promise<DomainsAutoConfigureStartMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        domainsAutoConfigureStart(
          client$,
          createDomainConnectApplyUrlDto,
          domain,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
