/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { domainsRoutesTest } from "../funcs/domainsRoutesTest.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type DomainsRoutesTestMutationVariables = {
  testDomainRouteDto: components.TestDomainRouteDto
  domain: string
  address: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type DomainsRoutesTestMutationData =
  operations.DomainsControllerTestDomainRouteResponse

export type DomainsRoutesTestMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Test an inbound route
 *
 * @remarks
 * Sends a synthetic inbound email through the same delivery path as production (outbound webhooks for webhook routes, signed HTTP to the agent for agent routes). Use `dryRun: true` to preview the payload without delivering.
 */
export function useDomainsRoutesTestMutation(
  options?: MutationHookOptions<
    DomainsRoutesTestMutationData,
    DomainsRoutesTestMutationError,
    DomainsRoutesTestMutationVariables
  >
): UseMutationResult<
  DomainsRoutesTestMutationData,
  DomainsRoutesTestMutationError,
  DomainsRoutesTestMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildDomainsRoutesTestMutation(client, options),
    ...options,
  })
}

export function mutationKeyDomainsRoutesTest(): MutationKey {
  return ["@novu/api", "Routes", "test"]
}

export function buildDomainsRoutesTestMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: DomainsRoutesTestMutationVariables
  ) => Promise<DomainsRoutesTestMutationData>
} {
  return {
    mutationKey: mutationKeyDomainsRoutesTest(),
    mutationFn: function domainsRoutesTestMutationFn({
      testDomainRouteDto,
      domain,
      address,
      idempotencyKey,
      options,
    }): Promise<DomainsRoutesTestMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        domainsRoutesTest(
          client$,
          testDomainRouteDto,
          domain,
          address,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
