/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { domainsDiagnose } from "../funcs/domainsDiagnose.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type DomainsDiagnoseMutationVariables = {
  domain: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type DomainsDiagnoseMutationData =
  operations.DomainsControllerDiagnoseDomainResponse

export type DomainsDiagnoseMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Diagnose inbound DNS for a domain
 *
 * @remarks
 * Runs live DNS checks for inbound email readiness (MX correctness, apex CNAME collision, and common DNS blocklists for the Novu mail host). Returns structured issues with plain-language fixes.
 */
export function useDomainsDiagnoseMutation(
  options?: MutationHookOptions<
    DomainsDiagnoseMutationData,
    DomainsDiagnoseMutationError,
    DomainsDiagnoseMutationVariables
  >
): UseMutationResult<
  DomainsDiagnoseMutationData,
  DomainsDiagnoseMutationError,
  DomainsDiagnoseMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildDomainsDiagnoseMutation(client, options),
    ...options,
  })
}

export function mutationKeyDomainsDiagnose(): MutationKey {
  return ["@novu/api", "Domains", "diagnose"]
}

export function buildDomainsDiagnoseMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: DomainsDiagnoseMutationVariables
  ) => Promise<DomainsDiagnoseMutationData>
} {
  return {
    mutationKey: mutationKeyDomainsDiagnose(),
    mutationFn: function domainsDiagnoseMutationFn({
      domain,
      idempotencyKey,
      options,
    }): Promise<DomainsDiagnoseMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        domainsDiagnose(client$, domain, idempotencyKey, mergedOptions)
      )
    },
  }
}
