/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { domainsUpdate } from "../funcs/domainsUpdate.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type DomainsUpdateMutationVariables = {
  updateDomainDto: components.UpdateDomainDto
  domain: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type DomainsUpdateMutationData =
  operations.DomainsControllerUpdateDomainResponse

export type DomainsUpdateMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Update a domain
 *
 * @remarks
 * Updates optional domain fields. When `data` is provided, it replaces the entire metadata object; omit `data` to leave it unchanged.
 */
export function useDomainsUpdateMutation(
  options?: MutationHookOptions<
    DomainsUpdateMutationData,
    DomainsUpdateMutationError,
    DomainsUpdateMutationVariables
  >
): UseMutationResult<
  DomainsUpdateMutationData,
  DomainsUpdateMutationError,
  DomainsUpdateMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildDomainsUpdateMutation(client, options),
    ...options,
  })
}

export function mutationKeyDomainsUpdate(): MutationKey {
  return ["@novu/api", "Domains", "update"]
}

export function buildDomainsUpdateMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: DomainsUpdateMutationVariables
  ) => Promise<DomainsUpdateMutationData>
} {
  return {
    mutationKey: mutationKeyDomainsUpdate(),
    mutationFn: function domainsUpdateMutationFn({
      updateDomainDto,
      domain,
      idempotencyKey,
      options,
    }): Promise<DomainsUpdateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        domainsUpdate(
          client$,
          updateDomainDto,
          domain,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
