/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { environmentsCreate } from "../funcs/environmentsCreate.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type EnvironmentsCreateMutationVariables = {
  createEnvironmentRequestDto: components.CreateEnvironmentRequestDto
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type EnvironmentsCreateMutationData =
  operations.EnvironmentsControllerV1CreateEnvironmentResponse

export type EnvironmentsCreateMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Create an environment
 *
 * @remarks
 * Creates a new environment within the current organization.
 *     Environments allow you to manage different stages of your application development lifecycle.
 *     Each environment has its own set of API keys and configurations.
 */
export function useEnvironmentsCreateMutation(
  options?: MutationHookOptions<
    EnvironmentsCreateMutationData,
    EnvironmentsCreateMutationError,
    EnvironmentsCreateMutationVariables
  >
): UseMutationResult<
  EnvironmentsCreateMutationData,
  EnvironmentsCreateMutationError,
  EnvironmentsCreateMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildEnvironmentsCreateMutation(client, options),
    ...options,
  })
}

export function mutationKeyEnvironmentsCreate(): MutationKey {
  return ["@novu/api", "Environments", "create"]
}

export function buildEnvironmentsCreateMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: EnvironmentsCreateMutationVariables
  ) => Promise<EnvironmentsCreateMutationData>
} {
  return {
    mutationKey: mutationKeyEnvironmentsCreate(),
    mutationFn: function environmentsCreateMutationFn({
      createEnvironmentRequestDto,
      idempotencyKey,
      options,
    }): Promise<EnvironmentsCreateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        environmentsCreate(
          client$,
          createEnvironmentRequestDto,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
