/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { environmentsPublish } from "../funcs/environmentsPublish.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type EnvironmentsPublishMutationVariables = {
  publishEnvironmentRequestDto: components.PublishEnvironmentRequestDto
  targetEnvironmentId: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type EnvironmentsPublishMutationData =
  operations.EnvironmentsControllerPublishEnvironmentResponse

export type EnvironmentsPublishMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Publish resources to target environment
 *
 * @remarks
 * Publishes all workflows and resources from the source environment to the target environment. Optionally specify specific resources to publish or use dryRun mode to preview changes.
 */
export function useEnvironmentsPublishMutation(
  options?: MutationHookOptions<
    EnvironmentsPublishMutationData,
    EnvironmentsPublishMutationError,
    EnvironmentsPublishMutationVariables
  >
): UseMutationResult<
  EnvironmentsPublishMutationData,
  EnvironmentsPublishMutationError,
  EnvironmentsPublishMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildEnvironmentsPublishMutation(client, options),
    ...options,
  })
}

export function mutationKeyEnvironmentsPublish(): MutationKey {
  return ["@novu/api", "Environments", "publish"]
}

export function buildEnvironmentsPublishMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: EnvironmentsPublishMutationVariables
  ) => Promise<EnvironmentsPublishMutationData>
} {
  return {
    mutationKey: mutationKeyEnvironmentsPublish(),
    mutationFn: function environmentsPublishMutationFn({
      publishEnvironmentRequestDto,
      targetEnvironmentId,
      idempotencyKey,
      options,
    }): Promise<EnvironmentsPublishMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        environmentsPublish(
          client$,
          publishEnvironmentRequestDto,
          targetEnvironmentId,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
