/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { environmentVariablesDelete } from "../funcs/environmentVariablesDelete.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type EnvironmentVariablesDeleteMutationVariables = {
  variableKey: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type EnvironmentVariablesDeleteMutationData =
  | operations.EnvironmentVariablesControllerDeleteEnvironmentVariableResponse
  | undefined

export type EnvironmentVariablesDeleteMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Delete environment variable
 *
 * @remarks
 * Deletes an environment variable by key.
 */
export function useEnvironmentVariablesDeleteMutation(
  options?: MutationHookOptions<
    EnvironmentVariablesDeleteMutationData,
    EnvironmentVariablesDeleteMutationError,
    EnvironmentVariablesDeleteMutationVariables
  >
): UseMutationResult<
  EnvironmentVariablesDeleteMutationData,
  EnvironmentVariablesDeleteMutationError,
  EnvironmentVariablesDeleteMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildEnvironmentVariablesDeleteMutation(client, options),
    ...options,
  })
}

export function mutationKeyEnvironmentVariablesDelete(): MutationKey {
  return ["@novu/api", "Environment Variables", "delete"]
}

export function buildEnvironmentVariablesDeleteMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: EnvironmentVariablesDeleteMutationVariables
  ) => Promise<EnvironmentVariablesDeleteMutationData>
} {
  return {
    mutationKey: mutationKeyEnvironmentVariablesDelete(),
    mutationFn: function environmentVariablesDeleteMutationFn({
      variableKey,
      idempotencyKey,
      options,
    }): Promise<EnvironmentVariablesDeleteMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        environmentVariablesDelete(
          client$,
          variableKey,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
