/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { integrationsUpdate } from "../funcs/integrationsUpdate.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type IntegrationsUpdateMutationVariables = {
  updateIntegrationRequestDto: components.UpdateIntegrationRequestDto
  integrationId: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type IntegrationsUpdateMutationData =
  operations.IntegrationsControllerUpdateIntegrationByIdResponse

export type IntegrationsUpdateMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Update an integration
 *
 * @remarks
 * Update an integration by its unique key identifier **integrationId**.
 *     Each provider supports different credentials, check the provider documentation for more details.
 */
export function useIntegrationsUpdateMutation(
  options?: MutationHookOptions<
    IntegrationsUpdateMutationData,
    IntegrationsUpdateMutationError,
    IntegrationsUpdateMutationVariables
  >
): UseMutationResult<
  IntegrationsUpdateMutationData,
  IntegrationsUpdateMutationError,
  IntegrationsUpdateMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildIntegrationsUpdateMutation(client, options),
    ...options,
  })
}

export function mutationKeyIntegrationsUpdate(): MutationKey {
  return ["@novu/api", "Integrations", "update"]
}

export function buildIntegrationsUpdateMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: IntegrationsUpdateMutationVariables
  ) => Promise<IntegrationsUpdateMutationData>
} {
  return {
    mutationKey: mutationKeyIntegrationsUpdate(),
    mutationFn: function integrationsUpdateMutationFn({
      updateIntegrationRequestDto,
      integrationId,
      idempotencyKey,
      options,
    }): Promise<IntegrationsUpdateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        integrationsUpdate(
          client$,
          updateIntegrationRequestDto,
          integrationId,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
