/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { integrationsGenerateConnectOAuthUrl } from "../funcs/integrationsGenerateConnectOAuthUrl.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type IntegrationsGenerateConnectOAuthUrlMutationVariables = {
  generateConnectOauthUrlRequestDto: components.GenerateConnectOauthUrlRequestDto
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type IntegrationsGenerateConnectOAuthUrlMutationData =
  operations.IntegrationsControllerGenerateConnectOAuthUrlResponse

export type IntegrationsGenerateConnectOAuthUrlMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Generate OAuth URL for a workspace/tenant connection
 *
 * @remarks
 * Generate an OAuth URL that creates a workspace or tenant-level channel connection (Slack workspace install or MS Teams admin consent).
 *     The generated URL expires after 5 minutes.
 */
export function useIntegrationsGenerateConnectOAuthUrlMutation(
  options?: MutationHookOptions<
    IntegrationsGenerateConnectOAuthUrlMutationData,
    IntegrationsGenerateConnectOAuthUrlMutationError,
    IntegrationsGenerateConnectOAuthUrlMutationVariables
  >
): UseMutationResult<
  IntegrationsGenerateConnectOAuthUrlMutationData,
  IntegrationsGenerateConnectOAuthUrlMutationError,
  IntegrationsGenerateConnectOAuthUrlMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildIntegrationsGenerateConnectOAuthUrlMutation(client, options),
    ...options,
  })
}

export function mutationKeyIntegrationsGenerateConnectOAuthUrl(): MutationKey {
  return ["@novu/api", "Integrations", "generateConnectOAuthUrl"]
}

export function buildIntegrationsGenerateConnectOAuthUrlMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: IntegrationsGenerateConnectOAuthUrlMutationVariables
  ) => Promise<IntegrationsGenerateConnectOAuthUrlMutationData>
} {
  return {
    mutationKey: mutationKeyIntegrationsGenerateConnectOAuthUrl(),
    mutationFn: function integrationsGenerateConnectOAuthUrlMutationFn({
      generateConnectOauthUrlRequestDto,
      idempotencyKey,
      options,
    }): Promise<IntegrationsGenerateConnectOAuthUrlMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        integrationsGenerateConnectOAuthUrl(
          client$,
          generateConnectOauthUrlRequestDto,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
