/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { layoutsDuplicate } from "../funcs/layoutsDuplicate.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type LayoutsDuplicateMutationVariables = {
  duplicateLayoutDto: components.DuplicateLayoutDto
  layoutId: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type LayoutsDuplicateMutationData =
  operations.LayoutsControllerDuplicateResponse

export type LayoutsDuplicateMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Duplicate a layout
 *
 * @remarks
 * Duplicates a layout by its unique identifier **layoutId**. This will create a new layout with the content of the original layout.
 */
export function useLayoutsDuplicateMutation(
  options?: MutationHookOptions<
    LayoutsDuplicateMutationData,
    LayoutsDuplicateMutationError,
    LayoutsDuplicateMutationVariables
  >
): UseMutationResult<
  LayoutsDuplicateMutationData,
  LayoutsDuplicateMutationError,
  LayoutsDuplicateMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildLayoutsDuplicateMutation(client, options),
    ...options,
  })
}

export function mutationKeyLayoutsDuplicate(): MutationKey {
  return ["@novu/api", "Layouts", "duplicate"]
}

export function buildLayoutsDuplicateMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: LayoutsDuplicateMutationVariables
  ) => Promise<LayoutsDuplicateMutationData>
} {
  return {
    mutationKey: mutationKeyLayoutsDuplicate(),
    mutationFn: function layoutsDuplicateMutationFn({
      duplicateLayoutDto,
      layoutId,
      idempotencyKey,
      options,
    }): Promise<LayoutsDuplicateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        layoutsDuplicate(
          client$,
          duplicateLayoutDto,
          layoutId,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
