/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { layoutsUpdate } from "../funcs/layoutsUpdate.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type LayoutsUpdateMutationVariables = {
  updateLayoutDto: components.UpdateLayoutDto
  layoutId: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type LayoutsUpdateMutationData =
  operations.LayoutsControllerUpdateResponse

export type LayoutsUpdateMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Update a layout
 *
 * @remarks
 * Updates the details of an existing layout, here **layoutId** is the identifier of the layout
 */
export function useLayoutsUpdateMutation(
  options?: MutationHookOptions<
    LayoutsUpdateMutationData,
    LayoutsUpdateMutationError,
    LayoutsUpdateMutationVariables
  >
): UseMutationResult<
  LayoutsUpdateMutationData,
  LayoutsUpdateMutationError,
  LayoutsUpdateMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildLayoutsUpdateMutation(client, options),
    ...options,
  })
}

export function mutationKeyLayoutsUpdate(): MutationKey {
  return ["@novu/api", "Layouts", "update"]
}

export function buildLayoutsUpdateMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: LayoutsUpdateMutationVariables
  ) => Promise<LayoutsUpdateMutationData>
} {
  return {
    mutationKey: mutationKeyLayoutsUpdate(),
    mutationFn: function layoutsUpdateMutationFn({
      updateLayoutDto,
      layoutId,
      idempotencyKey,
      options,
    }): Promise<LayoutsUpdateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        layoutsUpdate(
          client$,
          updateLayoutDto,
          layoutId,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
