/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { messagesDeleteByTransactionId } from "../funcs/messagesDeleteByTransactionId.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type MessagesDeleteByTransactionIdMutationVariables = {
  transactionId: string
  channel?:
    | operations.MessagesControllerDeleteMessagesByTransactionIdQueryParamChannel
    | undefined
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type MessagesDeleteByTransactionIdMutationData =
  | operations.MessagesControllerDeleteMessagesByTransactionIdResponse
  | undefined

export type MessagesDeleteByTransactionIdMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Delete messages by transactionId
 *
 * @remarks
 * Delete multiple messages from the Novu platform using **transactionId** of triggered event.
 *     This API supports filtering by **channel** and delete all messages associated with the **transactionId**.
 */
export function useMessagesDeleteByTransactionIdMutation(
  options?: MutationHookOptions<
    MessagesDeleteByTransactionIdMutationData,
    MessagesDeleteByTransactionIdMutationError,
    MessagesDeleteByTransactionIdMutationVariables
  >
): UseMutationResult<
  MessagesDeleteByTransactionIdMutationData,
  MessagesDeleteByTransactionIdMutationError,
  MessagesDeleteByTransactionIdMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildMessagesDeleteByTransactionIdMutation(client, options),
    ...options,
  })
}

export function mutationKeyMessagesDeleteByTransactionId(): MutationKey {
  return ["@novu/api", "Messages", "deleteByTransactionId"]
}

export function buildMessagesDeleteByTransactionIdMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: MessagesDeleteByTransactionIdMutationVariables
  ) => Promise<MessagesDeleteByTransactionIdMutationData>
} {
  return {
    mutationKey: mutationKeyMessagesDeleteByTransactionId(),
    mutationFn: function messagesDeleteByTransactionIdMutationFn({
      transactionId,
      channel,
      idempotencyKey,
      options,
    }): Promise<MessagesDeleteByTransactionIdMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        messagesDeleteByTransactionId(
          client$,
          transactionId,
          channel,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
