/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { messagesDelete } from "../funcs/messagesDelete.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type MessagesDeleteMutationVariables = {
  messageId: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type MessagesDeleteMutationData =
  operations.MessagesControllerDeleteMessageResponse

export type MessagesDeleteMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Delete a message
 *
 * @remarks
 * Delete a message entity from the Novu platform by **messageId**.
 *     This action is irreversible. **messageId** is required and of mongodbId type.
 */
export function useMessagesDeleteMutation(
  options?: MutationHookOptions<
    MessagesDeleteMutationData,
    MessagesDeleteMutationError,
    MessagesDeleteMutationVariables
  >
): UseMutationResult<
  MessagesDeleteMutationData,
  MessagesDeleteMutationError,
  MessagesDeleteMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildMessagesDeleteMutation(client, options),
    ...options,
  })
}

export function mutationKeyMessagesDelete(): MutationKey {
  return ["@novu/api", "Messages", "delete"]
}

export function buildMessagesDeleteMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: MessagesDeleteMutationVariables
  ) => Promise<MessagesDeleteMutationData>
} {
  return {
    mutationKey: mutationKeyMessagesDelete(),
    mutationFn: function messagesDeleteMutationFn({
      messageId,
      idempotencyKey,
      options,
    }): Promise<MessagesDeleteMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        messagesDelete(client$, messageId, idempotencyKey, mergedOptions)
      )
    },
  }
}
