/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { subscribersDelete } from "../funcs/subscribersDelete.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type SubscribersDeleteMutationVariables = {
  subscriberId: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type SubscribersDeleteMutationData =
  operations.SubscribersControllerRemoveSubscriberResponse

export type SubscribersDeleteMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Delete a subscriber
 *
 * @remarks
 * Deletes a subscriber entity from the Novu platform along with associated messages, preferences, and topic subscriptions.
 *       **subscriberId** is a required field.
 */
export function useSubscribersDeleteMutation(
  options?: MutationHookOptions<
    SubscribersDeleteMutationData,
    SubscribersDeleteMutationError,
    SubscribersDeleteMutationVariables
  >
): UseMutationResult<
  SubscribersDeleteMutationData,
  SubscribersDeleteMutationError,
  SubscribersDeleteMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildSubscribersDeleteMutation(client, options),
    ...options,
  })
}

export function mutationKeySubscribersDelete(): MutationKey {
  return ["@novu/api", "Subscribers", "delete"]
}

export function buildSubscribersDeleteMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: SubscribersDeleteMutationVariables
  ) => Promise<SubscribersDeleteMutationData>
} {
  return {
    mutationKey: mutationKeySubscribersDelete(),
    mutationFn: function subscribersDeleteMutationFn({
      subscriberId,
      idempotencyKey,
      options,
    }): Promise<SubscribersDeleteMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        subscribersDelete(client$, subscriberId, idempotencyKey, mergedOptions)
      )
    },
  }
}
