/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { subscribersNotificationsSnooze } from "../funcs/subscribersNotificationsSnooze.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type SubscribersNotificationsSnoozeMutationVariables = {
  request: operations.SubscribersControllerSnoozeNotificationRequest
  options?: RequestOptions
}

export type SubscribersNotificationsSnoozeMutationData =
  operations.SubscribersControllerSnoozeNotificationResponse

export type SubscribersNotificationsSnoozeMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Snooze a notification
 *
 * @remarks
 * Snooze a specific in-app (inbox) notification by its unique identifier **notificationId** until a specified time.
 */
export function useSubscribersNotificationsSnoozeMutation(
  options?: MutationHookOptions<
    SubscribersNotificationsSnoozeMutationData,
    SubscribersNotificationsSnoozeMutationError,
    SubscribersNotificationsSnoozeMutationVariables
  >
): UseMutationResult<
  SubscribersNotificationsSnoozeMutationData,
  SubscribersNotificationsSnoozeMutationError,
  SubscribersNotificationsSnoozeMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildSubscribersNotificationsSnoozeMutation(client, options),
    ...options,
  })
}

export function mutationKeySubscribersNotificationsSnooze(): MutationKey {
  return ["@novu/api", "Notifications", "snooze"]
}

export function buildSubscribersNotificationsSnoozeMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: SubscribersNotificationsSnoozeMutationVariables
  ) => Promise<SubscribersNotificationsSnoozeMutationData>
} {
  return {
    mutationKey: mutationKeySubscribersNotificationsSnooze(),
    mutationFn: function subscribersNotificationsSnoozeMutationFn({
      request,
      options,
    }): Promise<SubscribersNotificationsSnoozeMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        subscribersNotificationsSnooze(client$, request, mergedOptions)
      )
    },
  }
}
