/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { subscribersCredentialsDelete } from "../funcs/subscribersCredentialsDelete.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type SubscribersCredentialsDeleteMutationVariables = {
  subscriberId: string
  providerId: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type SubscribersCredentialsDeleteMutationData =
  | operations.SubscribersV1ControllerDeleteSubscriberCredentialsResponse
  | undefined

export type SubscribersCredentialsDeleteMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Delete provider credentials
 *
 * @remarks
 * Delete subscriber credentials for a provider such as **slack** and **FCM** by **providerId**.
 *     This action is irreversible and will remove the credentials for the provider for particular **subscriberId**.
 */
export function useSubscribersCredentialsDeleteMutation(
  options?: MutationHookOptions<
    SubscribersCredentialsDeleteMutationData,
    SubscribersCredentialsDeleteMutationError,
    SubscribersCredentialsDeleteMutationVariables
  >
): UseMutationResult<
  SubscribersCredentialsDeleteMutationData,
  SubscribersCredentialsDeleteMutationError,
  SubscribersCredentialsDeleteMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildSubscribersCredentialsDeleteMutation(client, options),
    ...options,
  })
}

export function mutationKeySubscribersCredentialsDelete(): MutationKey {
  return ["@novu/api", "Credentials", "delete"]
}

export function buildSubscribersCredentialsDeleteMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: SubscribersCredentialsDeleteMutationVariables
  ) => Promise<SubscribersCredentialsDeleteMutationData>
} {
  return {
    mutationKey: mutationKeySubscribersCredentialsDelete(),
    mutationFn: function subscribersCredentialsDeleteMutationFn({
      subscriberId,
      providerId,
      idempotencyKey,
      options,
    }): Promise<SubscribersCredentialsDeleteMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        subscribersCredentialsDelete(
          client$,
          subscriberId,
          providerId,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
