/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { subscribersCredentialsUpdate } from "../funcs/subscribersCredentialsUpdate.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type SubscribersCredentialsUpdateMutationVariables = {
  updateSubscriberChannelRequestDto: components.UpdateSubscriberChannelRequestDto
  subscriberId: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type SubscribersCredentialsUpdateMutationData =
  operations.SubscribersV1ControllerUpdateSubscriberChannelResponse

export type SubscribersCredentialsUpdateMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Update provider credentials
 *
 * @remarks
 * Update credentials for a provider such as **slack** and **FCM**.
 *       **providerId** is required field. This API creates the **deviceTokens** or replaces the existing ones.
 */
export function useSubscribersCredentialsUpdateMutation(
  options?: MutationHookOptions<
    SubscribersCredentialsUpdateMutationData,
    SubscribersCredentialsUpdateMutationError,
    SubscribersCredentialsUpdateMutationVariables
  >
): UseMutationResult<
  SubscribersCredentialsUpdateMutationData,
  SubscribersCredentialsUpdateMutationError,
  SubscribersCredentialsUpdateMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildSubscribersCredentialsUpdateMutation(client, options),
    ...options,
  })
}

export function mutationKeySubscribersCredentialsUpdate(): MutationKey {
  return ["@novu/api", "Credentials", "update"]
}

export function buildSubscribersCredentialsUpdateMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: SubscribersCredentialsUpdateMutationVariables
  ) => Promise<SubscribersCredentialsUpdateMutationData>
} {
  return {
    mutationKey: mutationKeySubscribersCredentialsUpdate(),
    mutationFn: function subscribersCredentialsUpdateMutationFn({
      updateSubscriberChannelRequestDto,
      subscriberId,
      idempotencyKey,
      options,
    }): Promise<SubscribersCredentialsUpdateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        subscribersCredentialsUpdate(
          client$,
          updateSubscriberChannelRequestDto,
          subscriberId,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
