/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { subscribersPatch } from "../funcs/subscribersPatch.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type SubscribersPatchMutationVariables = {
  patchSubscriberRequestDto: components.PatchSubscriberRequestDto
  subscriberId: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type SubscribersPatchMutationData =
  operations.SubscribersControllerPatchSubscriberResponse

export type SubscribersPatchMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Update a subscriber
 *
 * @remarks
 * Update a subscriber by its unique key identifier **subscriberId**.
 *     **subscriberId** is a required field, rest other fields are optional
 */
export function useSubscribersPatchMutation(
  options?: MutationHookOptions<
    SubscribersPatchMutationData,
    SubscribersPatchMutationError,
    SubscribersPatchMutationVariables
  >
): UseMutationResult<
  SubscribersPatchMutationData,
  SubscribersPatchMutationError,
  SubscribersPatchMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildSubscribersPatchMutation(client, options),
    ...options,
  })
}

export function mutationKeySubscribersPatch(): MutationKey {
  return ["@novu/api", "Subscribers", "patch"]
}

export function buildSubscribersPatchMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: SubscribersPatchMutationVariables
  ) => Promise<SubscribersPatchMutationData>
} {
  return {
    mutationKey: mutationKeySubscribersPatch(),
    mutationFn: function subscribersPatchMutationFn({
      patchSubscriberRequestDto,
      subscriberId,
      idempotencyKey,
      options,
    }): Promise<SubscribersPatchMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        subscribersPatch(
          client$,
          patchSubscriberRequestDto,
          subscriberId,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
