/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { subscribersNotificationsUnsnooze } from "../funcs/subscribersNotificationsUnsnooze.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type SubscribersNotificationsUnsnoozeMutationVariables = {
  request: operations.SubscribersControllerUnsnoozeNotificationRequest
  options?: RequestOptions
}

export type SubscribersNotificationsUnsnoozeMutationData =
  operations.SubscribersControllerUnsnoozeNotificationResponse

export type SubscribersNotificationsUnsnoozeMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Unsnooze a notification
 *
 * @remarks
 * Unsnooze a specific in-app (inbox) notification by its unique identifier **notificationId**.
 */
export function useSubscribersNotificationsUnsnoozeMutation(
  options?: MutationHookOptions<
    SubscribersNotificationsUnsnoozeMutationData,
    SubscribersNotificationsUnsnoozeMutationError,
    SubscribersNotificationsUnsnoozeMutationVariables
  >
): UseMutationResult<
  SubscribersNotificationsUnsnoozeMutationData,
  SubscribersNotificationsUnsnoozeMutationError,
  SubscribersNotificationsUnsnoozeMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildSubscribersNotificationsUnsnoozeMutation(client, options),
    ...options,
  })
}

export function mutationKeySubscribersNotificationsUnsnooze(): MutationKey {
  return ["@novu/api", "Notifications", "unsnooze"]
}

export function buildSubscribersNotificationsUnsnoozeMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: SubscribersNotificationsUnsnoozeMutationVariables
  ) => Promise<SubscribersNotificationsUnsnoozeMutationData>
} {
  return {
    mutationKey: mutationKeySubscribersNotificationsUnsnooze(),
    mutationFn: function subscribersNotificationsUnsnoozeMutationFn({
      request,
      options,
    }): Promise<SubscribersNotificationsUnsnoozeMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        subscribersNotificationsUnsnooze(client$, request, mergedOptions)
      )
    },
  }
}
