/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { topicsUpdate } from "../funcs/topicsUpdate.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type TopicsUpdateMutationVariables = {
  updateTopicRequestDto: components.UpdateTopicRequestDto
  topicKey: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type TopicsUpdateMutationData =
  operations.TopicsControllerUpdateTopicResponse

export type TopicsUpdateMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Update a topic
 *
 * @remarks
 * Update a topic name by its unique key identifier **topicKey**
 */
export function useTopicsUpdateMutation(
  options?: MutationHookOptions<
    TopicsUpdateMutationData,
    TopicsUpdateMutationError,
    TopicsUpdateMutationVariables
  >
): UseMutationResult<
  TopicsUpdateMutationData,
  TopicsUpdateMutationError,
  TopicsUpdateMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildTopicsUpdateMutation(client, options),
    ...options,
  })
}

export function mutationKeyTopicsUpdate(): MutationKey {
  return ["@novu/api", "Topics", "update"]
}

export function buildTopicsUpdateMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: TopicsUpdateMutationVariables
  ) => Promise<TopicsUpdateMutationData>
} {
  return {
    mutationKey: mutationKeyTopicsUpdate(),
    mutationFn: function topicsUpdateMutationFn({
      updateTopicRequestDto,
      topicKey,
      idempotencyKey,
      options,
    }): Promise<TopicsUpdateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        topicsUpdate(
          client$,
          updateTopicRequestDto,
          topicKey,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
