/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { translationsMasterImport } from "../funcs/translationsMasterImport.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type TranslationsMasterImportMutationVariables = {
  importMasterJsonRequestDto: components.ImportMasterJsonRequestDto
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type TranslationsMasterImportMutationData =
  components.ImportMasterJsonResponseDto

export type TranslationsMasterImportMutationError =
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Import master translations JSON
 *
 * @remarks
 * Import translations for multiple workflows from master JSON format for a specific locale
 */
export function useTranslationsMasterImportMutation(
  options?: MutationHookOptions<
    TranslationsMasterImportMutationData,
    TranslationsMasterImportMutationError,
    TranslationsMasterImportMutationVariables
  >
): UseMutationResult<
  TranslationsMasterImportMutationData,
  TranslationsMasterImportMutationError,
  TranslationsMasterImportMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildTranslationsMasterImportMutation(client, options),
    ...options,
  })
}

export function mutationKeyTranslationsMasterImport(): MutationKey {
  return ["@novu/api", "master", "import"]
}

export function buildTranslationsMasterImportMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: TranslationsMasterImportMutationVariables
  ) => Promise<TranslationsMasterImportMutationData>
} {
  return {
    mutationKey: mutationKeyTranslationsMasterImport(),
    mutationFn: function translationsMasterImportMutationFn({
      importMasterJsonRequestDto,
      idempotencyKey,
      options,
    }): Promise<TranslationsMasterImportMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        translationsMasterImport(
          client$,
          importMasterJsonRequestDto,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
