/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { workflowsCreate } from "../funcs/workflowsCreate.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type WorkflowsCreateMutationVariables = {
  createWorkflowDto: components.CreateWorkflowDto
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type WorkflowsCreateMutationData =
  operations.WorkflowControllerCreateResponse

export type WorkflowsCreateMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Create a workflow
 *
 * @remarks
 * Creates a new workflow in the Novu Cloud environment
 */
export function useWorkflowsCreateMutation(
  options?: MutationHookOptions<
    WorkflowsCreateMutationData,
    WorkflowsCreateMutationError,
    WorkflowsCreateMutationVariables
  >
): UseMutationResult<
  WorkflowsCreateMutationData,
  WorkflowsCreateMutationError,
  WorkflowsCreateMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildWorkflowsCreateMutation(client, options),
    ...options,
  })
}

export function mutationKeyWorkflowsCreate(): MutationKey {
  return ["@novu/api", "Workflows", "create"]
}

export function buildWorkflowsCreateMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: WorkflowsCreateMutationVariables
  ) => Promise<WorkflowsCreateMutationData>
} {
  return {
    mutationKey: mutationKeyWorkflowsCreate(),
    mutationFn: function workflowsCreateMutationFn({
      createWorkflowDto,
      idempotencyKey,
      options,
    }): Promise<WorkflowsCreateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        workflowsCreate(
          client$,
          createWorkflowDto,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
