/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type InvalidateQueryFilters,
  type QueryClient,
  type UseQueryResult,
  type UseSuspenseQueryResult,
  useQuery,
  useSuspenseQuery,
} from "@tanstack/react-query"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import { useNovuContext } from "./_context.js"
import type {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js"
import {
  buildWorkflowsGetQuery,
  prefetchWorkflowsGet,
  queryKeyWorkflowsGet,
  type WorkflowsGetQueryData,
} from "./workflowsGet.core.js"

export {
  buildWorkflowsGetQuery,
  prefetchWorkflowsGet,
  queryKeyWorkflowsGet,
  type WorkflowsGetQueryData,
}

export type WorkflowsGetQueryError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Retrieve a workflow
 *
 * @remarks
 * Fetches details of a specific workflow by its unique identifier **workflowId**
 */
export function useWorkflowsGet(
  workflowId: string,
  environmentId?: string | undefined,
  idempotencyKey?: string | undefined,
  options?: QueryHookOptions<WorkflowsGetQueryData, WorkflowsGetQueryError>
): UseQueryResult<WorkflowsGetQueryData, WorkflowsGetQueryError> {
  const client = useNovuContext()
  return useQuery({
    ...buildWorkflowsGetQuery(
      client,
      workflowId,
      environmentId,
      idempotencyKey,
      options
    ),
    ...options,
  })
}

/**
 * Retrieve a workflow
 *
 * @remarks
 * Fetches details of a specific workflow by its unique identifier **workflowId**
 */
export function useWorkflowsGetSuspense(
  workflowId: string,
  environmentId?: string | undefined,
  idempotencyKey?: string | undefined,
  options?: SuspenseQueryHookOptions<
    WorkflowsGetQueryData,
    WorkflowsGetQueryError
  >
): UseSuspenseQueryResult<WorkflowsGetQueryData, WorkflowsGetQueryError> {
  const client = useNovuContext()
  return useSuspenseQuery({
    ...buildWorkflowsGetQuery(
      client,
      workflowId,
      environmentId,
      idempotencyKey,
      options
    ),
    ...options,
  })
}

export function setWorkflowsGetData(
  client: QueryClient,
  queryKeyBase: [
    workflowId: string,
    parameters: {
      environmentId?: string | undefined
      idempotencyKey?: string | undefined
    },
  ],
  data: WorkflowsGetQueryData
): WorkflowsGetQueryData | undefined {
  const key = queryKeyWorkflowsGet(...queryKeyBase)

  return client.setQueryData<WorkflowsGetQueryData>(key, data)
}

export function invalidateWorkflowsGet(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [
      workflowId: string,
      parameters: {
        environmentId?: string | undefined
        idempotencyKey?: string | undefined
      },
    ]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@novu/api", "Workflows", "get", ...queryKeyBase],
  })
}

export function invalidateAllWorkflowsGet(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@novu/api", "Workflows", "get"],
  })
}
