/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { channelConnectionsUpdate } from "../funcs/channelConnectionsUpdate.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type ChannelConnectionsUpdateMutationVariables = {
  updateChannelConnectionRequestDto: components.UpdateChannelConnectionRequestDto
  identifier: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type ChannelConnectionsUpdateMutationData =
  operations.ChannelConnectionsControllerUpdateChannelConnectionResponse

export type ChannelConnectionsUpdateMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Update a channel connection
 *
 * @remarks
 * Update an existing channel connection by its unique identifier.
 */
export function useChannelConnectionsUpdateMutation(
  options?: MutationHookOptions<
    ChannelConnectionsUpdateMutationData,
    ChannelConnectionsUpdateMutationError,
    ChannelConnectionsUpdateMutationVariables
  >
): UseMutationResult<
  ChannelConnectionsUpdateMutationData,
  ChannelConnectionsUpdateMutationError,
  ChannelConnectionsUpdateMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildChannelConnectionsUpdateMutation(client, options),
    ...options,
  })
}

export function mutationKeyChannelConnectionsUpdate(): MutationKey {
  return ["@novu/api", "Channel Connections", "update"]
}

export function buildChannelConnectionsUpdateMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: ChannelConnectionsUpdateMutationVariables
  ) => Promise<ChannelConnectionsUpdateMutationData>
} {
  return {
    mutationKey: mutationKeyChannelConnectionsUpdate(),
    mutationFn: function channelConnectionsUpdateMutationFn({
      updateChannelConnectionRequestDto,
      identifier,
      idempotencyKey,
      options,
    }): Promise<ChannelConnectionsUpdateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        channelConnectionsUpdate(
          client$,
          updateChannelConnectionRequestDto,
          identifier,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
