/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { channelConnectionsCreate } from "../funcs/channelConnectionsCreate.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type ChannelConnectionsCreateMutationVariables = {
  createChannelConnectionRequestDto: components.CreateChannelConnectionRequestDto
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type ChannelConnectionsCreateMutationData =
  operations.ChannelConnectionsControllerCreateChannelConnectionResponse

export type ChannelConnectionsCreateMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Create a channel connection
 *
 * @remarks
 * Create a new channel connection for a resource for given integration. Only one channel connection is allowed per resource and integration.
 */
export function useChannelConnectionsCreateMutation(
  options?: MutationHookOptions<
    ChannelConnectionsCreateMutationData,
    ChannelConnectionsCreateMutationError,
    ChannelConnectionsCreateMutationVariables
  >
): UseMutationResult<
  ChannelConnectionsCreateMutationData,
  ChannelConnectionsCreateMutationError,
  ChannelConnectionsCreateMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildChannelConnectionsCreateMutation(client, options),
    ...options,
  })
}

export function mutationKeyChannelConnectionsCreate(): MutationKey {
  return ["@novu/api", "Channel Connections", "create"]
}

export function buildChannelConnectionsCreateMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: ChannelConnectionsCreateMutationVariables
  ) => Promise<ChannelConnectionsCreateMutationData>
} {
  return {
    mutationKey: mutationKeyChannelConnectionsCreate(),
    mutationFn: function channelConnectionsCreateMutationFn({
      createChannelConnectionRequestDto,
      idempotencyKey,
      options,
    }): Promise<ChannelConnectionsCreateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        channelConnectionsCreate(
          client$,
          createChannelConnectionRequestDto,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
