/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { domainsRoutesUpdate } from "../funcs/domainsRoutesUpdate.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type DomainsRoutesUpdateMutationVariables = {
  updateDomainRouteDto: components.UpdateDomainRouteDto
  domain: string
  address: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type DomainsRoutesUpdateMutationData =
  operations.DomainsControllerUpdateDomainRouteResponse

export type DomainsRoutesUpdateMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Update a route
 *
 * @remarks
 * Updates the destination of the route bound to `<address>@<domain>`. The address itself is the resource identity and cannot be changed; delete and recreate the route to rename it.
 */
export function useDomainsRoutesUpdateMutation(
  options?: MutationHookOptions<
    DomainsRoutesUpdateMutationData,
    DomainsRoutesUpdateMutationError,
    DomainsRoutesUpdateMutationVariables
  >
): UseMutationResult<
  DomainsRoutesUpdateMutationData,
  DomainsRoutesUpdateMutationError,
  DomainsRoutesUpdateMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildDomainsRoutesUpdateMutation(client, options),
    ...options,
  })
}

export function mutationKeyDomainsRoutesUpdate(): MutationKey {
  return ["@novu/api", "Routes", "update"]
}

export function buildDomainsRoutesUpdateMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: DomainsRoutesUpdateMutationVariables
  ) => Promise<DomainsRoutesUpdateMutationData>
} {
  return {
    mutationKey: mutationKeyDomainsRoutesUpdate(),
    mutationFn: function domainsRoutesUpdateMutationFn({
      updateDomainRouteDto,
      domain,
      address,
      idempotencyKey,
      options,
    }): Promise<DomainsRoutesUpdateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        domainsRoutesUpdate(
          client$,
          updateDomainRouteDto,
          domain,
          address,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
