/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { domainsCreate } from "../funcs/domainsCreate.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type DomainsCreateMutationVariables = {
  createDomainDto: components.CreateDomainDto
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type DomainsCreateMutationData =
  operations.DomainsControllerCreateDomainResponse

export type DomainsCreateMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Create a domain
 *
 * @remarks
 * Registers a new inbound-email domain. The response includes the DNS records customers must add at their DNS provider before the domain can receive mail.
 */
export function useDomainsCreateMutation(
  options?: MutationHookOptions<
    DomainsCreateMutationData,
    DomainsCreateMutationError,
    DomainsCreateMutationVariables
  >
): UseMutationResult<
  DomainsCreateMutationData,
  DomainsCreateMutationError,
  DomainsCreateMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildDomainsCreateMutation(client, options),
    ...options,
  })
}

export function mutationKeyDomainsCreate(): MutationKey {
  return ["@novu/api", "Domains", "create"]
}

export function buildDomainsCreateMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: DomainsCreateMutationVariables
  ) => Promise<DomainsCreateMutationData>
} {
  return {
    mutationKey: mutationKeyDomainsCreate(),
    mutationFn: function domainsCreateMutationFn({
      createDomainDto,
      idempotencyKey,
      options,
    }): Promise<DomainsCreateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        domainsCreate(client$, createDomainDto, idempotencyKey, mergedOptions)
      )
    },
  }
}
