/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { domainsRoutesCreate } from "../funcs/domainsRoutesCreate.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type DomainsRoutesCreateMutationVariables = {
  domainRouteDto: components.DomainRouteDto
  domain: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type DomainsRoutesCreateMutationData =
  operations.DomainsControllerCreateDomainRouteResponse

export type DomainsRoutesCreateMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Create a route
 *
 * @remarks
 * Creates a route on the domain that forwards inbound mail addressed to `<address>@<domain>` to either a webhook or an agent. Each address on a domain may only have a single route.
 */
export function useDomainsRoutesCreateMutation(
  options?: MutationHookOptions<
    DomainsRoutesCreateMutationData,
    DomainsRoutesCreateMutationError,
    DomainsRoutesCreateMutationVariables
  >
): UseMutationResult<
  DomainsRoutesCreateMutationData,
  DomainsRoutesCreateMutationError,
  DomainsRoutesCreateMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildDomainsRoutesCreateMutation(client, options),
    ...options,
  })
}

export function mutationKeyDomainsRoutesCreate(): MutationKey {
  return ["@novu/api", "Routes", "create"]
}

export function buildDomainsRoutesCreateMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: DomainsRoutesCreateMutationVariables
  ) => Promise<DomainsRoutesCreateMutationData>
} {
  return {
    mutationKey: mutationKeyDomainsRoutesCreate(),
    mutationFn: function domainsRoutesCreateMutationFn({
      domainRouteDto,
      domain,
      idempotencyKey,
      options,
    }): Promise<DomainsRoutesCreateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        domainsRoutesCreate(
          client$,
          domainRouteDto,
          domain,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
