/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { environmentsDiff } from "../funcs/environmentsDiff.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type EnvironmentsDiffMutationVariables = {
  diffEnvironmentRequestDto: components.DiffEnvironmentRequestDto
  targetEnvironmentId: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type EnvironmentsDiffMutationData =
  operations.EnvironmentsControllerDiffEnvironmentResponse

export type EnvironmentsDiffMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Compare resources between environments
 *
 * @remarks
 * Compares workflows and other resources between the source and target environments, returning detailed diff information including additions, modifications, and deletions.
 */
export function useEnvironmentsDiffMutation(
  options?: MutationHookOptions<
    EnvironmentsDiffMutationData,
    EnvironmentsDiffMutationError,
    EnvironmentsDiffMutationVariables
  >
): UseMutationResult<
  EnvironmentsDiffMutationData,
  EnvironmentsDiffMutationError,
  EnvironmentsDiffMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildEnvironmentsDiffMutation(client, options),
    ...options,
  })
}

export function mutationKeyEnvironmentsDiff(): MutationKey {
  return ["@novu/api", "Environments", "diff"]
}

export function buildEnvironmentsDiffMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: EnvironmentsDiffMutationVariables
  ) => Promise<EnvironmentsDiffMutationData>
} {
  return {
    mutationKey: mutationKeyEnvironmentsDiff(),
    mutationFn: function environmentsDiffMutationFn({
      diffEnvironmentRequestDto,
      targetEnvironmentId,
      idempotencyKey,
      options,
    }): Promise<EnvironmentsDiffMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        environmentsDiff(
          client$,
          diffEnvironmentRequestDto,
          targetEnvironmentId,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
