/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { environmentsUpdate } from "../funcs/environmentsUpdate.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type EnvironmentsUpdateMutationVariables = {
  updateEnvironmentRequestDto: components.UpdateEnvironmentRequestDto
  environmentId: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type EnvironmentsUpdateMutationData =
  operations.EnvironmentsControllerV1UpdateMyEnvironmentResponse

export type EnvironmentsUpdateMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Update an environment
 *
 * @remarks
 * Update an environment by its unique identifier **environmentId**.
 *     You can modify the environment name, identifier, color, and other configuration settings.
 */
export function useEnvironmentsUpdateMutation(
  options?: MutationHookOptions<
    EnvironmentsUpdateMutationData,
    EnvironmentsUpdateMutationError,
    EnvironmentsUpdateMutationVariables
  >
): UseMutationResult<
  EnvironmentsUpdateMutationData,
  EnvironmentsUpdateMutationError,
  EnvironmentsUpdateMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildEnvironmentsUpdateMutation(client, options),
    ...options,
  })
}

export function mutationKeyEnvironmentsUpdate(): MutationKey {
  return ["@novu/api", "Environments", "update"]
}

export function buildEnvironmentsUpdateMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: EnvironmentsUpdateMutationVariables
  ) => Promise<EnvironmentsUpdateMutationData>
} {
  return {
    mutationKey: mutationKeyEnvironmentsUpdate(),
    mutationFn: function environmentsUpdateMutationFn({
      updateEnvironmentRequestDto,
      environmentId,
      idempotencyKey,
      options,
    }): Promise<EnvironmentsUpdateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        environmentsUpdate(
          client$,
          updateEnvironmentRequestDto,
          environmentId,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
