/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { integrationsGenerateChatOAuthUrl } from "../funcs/integrationsGenerateChatOAuthUrl.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type IntegrationsGenerateChatOAuthUrlMutationVariables = {
  generateChatOauthUrlRequestDto: components.GenerateChatOauthUrlRequestDto
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type IntegrationsGenerateChatOAuthUrlMutationData =
  operations.IntegrationsControllerGetChatOAuthUrlResponse

export type IntegrationsGenerateChatOAuthUrlMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Generate chat OAuth URL
 *
 * @remarks
 * **Deprecated** — use `POST /integrations/channel-connections/oauth` (connect) or `POST /integrations/channel-endpoints/oauth` (link_user) instead.
 *     Generate an OAuth URL for chat integrations like Slack and MS Teams.
 *     This URL allows subscribers to authorize the integration, enabling the system to send messages
 *     through their chat workspace. The generated URL expires after 5 minutes.
 *
 * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
 */
export function useIntegrationsGenerateChatOAuthUrlMutation(
  options?: MutationHookOptions<
    IntegrationsGenerateChatOAuthUrlMutationData,
    IntegrationsGenerateChatOAuthUrlMutationError,
    IntegrationsGenerateChatOAuthUrlMutationVariables
  >
): UseMutationResult<
  IntegrationsGenerateChatOAuthUrlMutationData,
  IntegrationsGenerateChatOAuthUrlMutationError,
  IntegrationsGenerateChatOAuthUrlMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildIntegrationsGenerateChatOAuthUrlMutation(client, options),
    ...options,
  })
}

export function mutationKeyIntegrationsGenerateChatOAuthUrl(): MutationKey {
  return ["@novu/api", "Integrations", "generateChatOAuthUrl"]
}

export function buildIntegrationsGenerateChatOAuthUrlMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: IntegrationsGenerateChatOAuthUrlMutationVariables
  ) => Promise<IntegrationsGenerateChatOAuthUrlMutationData>
} {
  return {
    mutationKey: mutationKeyIntegrationsGenerateChatOAuthUrl(),
    mutationFn: function integrationsGenerateChatOAuthUrlMutationFn({
      generateChatOauthUrlRequestDto,
      idempotencyKey,
      options,
    }): Promise<IntegrationsGenerateChatOAuthUrlMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        integrationsGenerateChatOAuthUrl(
          client$,
          generateChatOauthUrlRequestDto,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
