/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { layoutsDelete } from "../funcs/layoutsDelete.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type LayoutsDeleteMutationVariables = {
  layoutId: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type LayoutsDeleteMutationData =
  | operations.LayoutsControllerDeleteResponse
  | undefined

export type LayoutsDeleteMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Delete a layout
 *
 * @remarks
 * Removes a specific layout by its unique identifier **layoutId**
 */
export function useLayoutsDeleteMutation(
  options?: MutationHookOptions<
    LayoutsDeleteMutationData,
    LayoutsDeleteMutationError,
    LayoutsDeleteMutationVariables
  >
): UseMutationResult<
  LayoutsDeleteMutationData,
  LayoutsDeleteMutationError,
  LayoutsDeleteMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildLayoutsDeleteMutation(client, options),
    ...options,
  })
}

export function mutationKeyLayoutsDelete(): MutationKey {
  return ["@novu/api", "Layouts", "delete"]
}

export function buildLayoutsDeleteMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: LayoutsDeleteMutationVariables
  ) => Promise<LayoutsDeleteMutationData>
} {
  return {
    mutationKey: mutationKeyLayoutsDelete(),
    mutationFn: function layoutsDeleteMutationFn({
      layoutId,
      idempotencyKey,
      options,
    }): Promise<LayoutsDeleteMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        layoutsDelete(client$, layoutId, idempotencyKey, mergedOptions)
      )
    },
  }
}
