/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { subscribersNotificationsUnarchive } from "../funcs/subscribersNotificationsUnarchive.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type SubscribersNotificationsUnarchiveMutationVariables = {
  request: operations.SubscribersControllerUnarchiveNotificationRequest
  options?: RequestOptions
}

export type SubscribersNotificationsUnarchiveMutationData =
  operations.SubscribersControllerUnarchiveNotificationResponse

export type SubscribersNotificationsUnarchiveMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Unarchive a notification
 *
 * @remarks
 * Unarchive a specific in-app (inbox) notification by its unique identifier **notificationId**.
 */
export function useSubscribersNotificationsUnarchiveMutation(
  options?: MutationHookOptions<
    SubscribersNotificationsUnarchiveMutationData,
    SubscribersNotificationsUnarchiveMutationError,
    SubscribersNotificationsUnarchiveMutationVariables
  >
): UseMutationResult<
  SubscribersNotificationsUnarchiveMutationData,
  SubscribersNotificationsUnarchiveMutationError,
  SubscribersNotificationsUnarchiveMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildSubscribersNotificationsUnarchiveMutation(client, options),
    ...options,
  })
}

export function mutationKeySubscribersNotificationsUnarchive(): MutationKey {
  return ["@novu/api", "Notifications", "unarchive"]
}

export function buildSubscribersNotificationsUnarchiveMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: SubscribersNotificationsUnarchiveMutationVariables
  ) => Promise<SubscribersNotificationsUnarchiveMutationData>
} {
  return {
    mutationKey: mutationKeySubscribersNotificationsUnarchive(),
    mutationFn: function subscribersNotificationsUnarchiveMutationFn({
      request,
      options,
    }): Promise<SubscribersNotificationsUnarchiveMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        subscribersNotificationsUnarchive(client$, request, mergedOptions)
      )
    },
  }
}
