/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { subscribersNotificationsCompleteAction } from "../funcs/subscribersNotificationsCompleteAction.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type SubscribersNotificationsCompleteActionMutationVariables = {
  request: operations.SubscribersControllerCompleteNotificationActionRequest
  options?: RequestOptions
}

export type SubscribersNotificationsCompleteActionMutationData =
  operations.SubscribersControllerCompleteNotificationActionResponse

export type SubscribersNotificationsCompleteActionMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Complete a notification action
 *
 * @remarks
 * Mark a single in-app (inbox) notification's action (primary or secondary) as completed by its unique identifier **notificationId** and action type **actionType**.
 */
export function useSubscribersNotificationsCompleteActionMutation(
  options?: MutationHookOptions<
    SubscribersNotificationsCompleteActionMutationData,
    SubscribersNotificationsCompleteActionMutationError,
    SubscribersNotificationsCompleteActionMutationVariables
  >
): UseMutationResult<
  SubscribersNotificationsCompleteActionMutationData,
  SubscribersNotificationsCompleteActionMutationError,
  SubscribersNotificationsCompleteActionMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildSubscribersNotificationsCompleteActionMutation(client, options),
    ...options,
  })
}

export function mutationKeySubscribersNotificationsCompleteAction(): MutationKey {
  return ["@novu/api", "Notifications", "completeAction"]
}

export function buildSubscribersNotificationsCompleteActionMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: SubscribersNotificationsCompleteActionMutationVariables
  ) => Promise<SubscribersNotificationsCompleteActionMutationData>
} {
  return {
    mutationKey: mutationKeySubscribersNotificationsCompleteAction(),
    mutationFn: function subscribersNotificationsCompleteActionMutationFn({
      request,
      options,
    }): Promise<SubscribersNotificationsCompleteActionMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        subscribersNotificationsCompleteAction(client$, request, mergedOptions)
      )
    },
  }
}
