/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { subscribersMessagesMarkAllAs } from "../funcs/subscribersMessagesMarkAllAs.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type SubscribersMessagesMarkAllAsMutationVariables = {
  messageMarkAsRequestDto: components.MessageMarkAsRequestDto
  subscriberId: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type SubscribersMessagesMarkAllAsMutationData =
  operations.SubscribersV1ControllerMarkMessagesAsResponse

export type SubscribersMessagesMarkAllAsMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Update notifications state
 *
 * @remarks
 * Update subscriber's multiple in-app (inbox) notifications state such as seen, read, unseen or unread by **subscriberId**.
 *       **messageId** is of type mongodbId of notifications
 */
export function useSubscribersMessagesMarkAllAsMutation(
  options?: MutationHookOptions<
    SubscribersMessagesMarkAllAsMutationData,
    SubscribersMessagesMarkAllAsMutationError,
    SubscribersMessagesMarkAllAsMutationVariables
  >
): UseMutationResult<
  SubscribersMessagesMarkAllAsMutationData,
  SubscribersMessagesMarkAllAsMutationError,
  SubscribersMessagesMarkAllAsMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildSubscribersMessagesMarkAllAsMutation(client, options),
    ...options,
  })
}

export function mutationKeySubscribersMessagesMarkAllAs(): MutationKey {
  return ["@novu/api", "Messages", "markAllAs"]
}

export function buildSubscribersMessagesMarkAllAsMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: SubscribersMessagesMarkAllAsMutationVariables
  ) => Promise<SubscribersMessagesMarkAllAsMutationData>
} {
  return {
    mutationKey: mutationKeySubscribersMessagesMarkAllAs(),
    mutationFn: function subscribersMessagesMarkAllAsMutationFn({
      messageMarkAsRequestDto,
      subscriberId,
      idempotencyKey,
      options,
    }): Promise<SubscribersMessagesMarkAllAsMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        subscribersMessagesMarkAllAs(
          client$,
          messageMarkAsRequestDto,
          subscriberId,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
