/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { subscribersCredentialsAppend } from "../funcs/subscribersCredentialsAppend.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type SubscribersCredentialsAppendMutationVariables = {
  updateSubscriberChannelRequestDto: components.UpdateSubscriberChannelRequestDto
  subscriberId: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type SubscribersCredentialsAppendMutationData =
  operations.SubscribersV1ControllerModifySubscriberChannelResponse

export type SubscribersCredentialsAppendMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Upsert provider credentials
 *
 * @remarks
 * Upsert credentials for a provider such as **slack** and **FCM**.
 *       **providerId** is required field. This API creates **deviceTokens** or appends to the existing ones.
 */
export function useSubscribersCredentialsAppendMutation(
  options?: MutationHookOptions<
    SubscribersCredentialsAppendMutationData,
    SubscribersCredentialsAppendMutationError,
    SubscribersCredentialsAppendMutationVariables
  >
): UseMutationResult<
  SubscribersCredentialsAppendMutationData,
  SubscribersCredentialsAppendMutationError,
  SubscribersCredentialsAppendMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildSubscribersCredentialsAppendMutation(client, options),
    ...options,
  })
}

export function mutationKeySubscribersCredentialsAppend(): MutationKey {
  return ["@novu/api", "Credentials", "append"]
}

export function buildSubscribersCredentialsAppendMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: SubscribersCredentialsAppendMutationVariables
  ) => Promise<SubscribersCredentialsAppendMutationData>
} {
  return {
    mutationKey: mutationKeySubscribersCredentialsAppend(),
    mutationFn: function subscribersCredentialsAppendMutationFn({
      updateSubscriberChannelRequestDto,
      subscriberId,
      idempotencyKey,
      options,
    }): Promise<SubscribersCredentialsAppendMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        subscribersCredentialsAppend(
          client$,
          updateSubscriberChannelRequestDto,
          subscriberId,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
