/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { subscribersPreferencesBulkUpdate } from "../funcs/subscribersPreferencesBulkUpdate.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type SubscribersPreferencesBulkUpdateMutationVariables = {
  bulkUpdateSubscriberPreferencesDto: components.BulkUpdateSubscriberPreferencesDto
  subscriberId: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type SubscribersPreferencesBulkUpdateMutationData =
  operations.SubscribersControllerBulkUpdateSubscriberPreferencesResponse

export type SubscribersPreferencesBulkUpdateMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Bulk update subscriber preferences
 *
 * @remarks
 * Bulk update subscriber preferences by its unique key identifier **subscriberId**.
 *     This API allows updating multiple workflow preferences in a single request.
 */
export function useSubscribersPreferencesBulkUpdateMutation(
  options?: MutationHookOptions<
    SubscribersPreferencesBulkUpdateMutationData,
    SubscribersPreferencesBulkUpdateMutationError,
    SubscribersPreferencesBulkUpdateMutationVariables
  >
): UseMutationResult<
  SubscribersPreferencesBulkUpdateMutationData,
  SubscribersPreferencesBulkUpdateMutationError,
  SubscribersPreferencesBulkUpdateMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildSubscribersPreferencesBulkUpdateMutation(client, options),
    ...options,
  })
}

export function mutationKeySubscribersPreferencesBulkUpdate(): MutationKey {
  return ["@novu/api", "Preferences", "bulkUpdate"]
}

export function buildSubscribersPreferencesBulkUpdateMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: SubscribersPreferencesBulkUpdateMutationVariables
  ) => Promise<SubscribersPreferencesBulkUpdateMutationData>
} {
  return {
    mutationKey: mutationKeySubscribersPreferencesBulkUpdate(),
    mutationFn: function subscribersPreferencesBulkUpdateMutationFn({
      bulkUpdateSubscriberPreferencesDto,
      subscriberId,
      idempotencyKey,
      options,
    }): Promise<SubscribersPreferencesBulkUpdateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        subscribersPreferencesBulkUpdate(
          client$,
          bulkUpdateSubscriberPreferencesDto,
          subscriberId,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
