/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { subscribersPreferencesUpdate } from "../funcs/subscribersPreferencesUpdate.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type SubscribersPreferencesUpdateMutationVariables = {
  patchSubscriberPreferencesDto: components.PatchSubscriberPreferencesDto
  subscriberId: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type SubscribersPreferencesUpdateMutationData =
  operations.SubscribersControllerUpdateSubscriberPreferencesResponse

export type SubscribersPreferencesUpdateMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Update subscriber preferences
 *
 * @remarks
 * Update subscriber preferences by its unique key identifier **subscriberId**.
 *     **workflowId** is optional field, if provided, this API will update that workflow preference,
 *     otherwise it will update global preferences
 */
export function useSubscribersPreferencesUpdateMutation(
  options?: MutationHookOptions<
    SubscribersPreferencesUpdateMutationData,
    SubscribersPreferencesUpdateMutationError,
    SubscribersPreferencesUpdateMutationVariables
  >
): UseMutationResult<
  SubscribersPreferencesUpdateMutationData,
  SubscribersPreferencesUpdateMutationError,
  SubscribersPreferencesUpdateMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildSubscribersPreferencesUpdateMutation(client, options),
    ...options,
  })
}

export function mutationKeySubscribersPreferencesUpdate(): MutationKey {
  return ["@novu/api", "Preferences", "update"]
}

export function buildSubscribersPreferencesUpdateMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: SubscribersPreferencesUpdateMutationVariables
  ) => Promise<SubscribersPreferencesUpdateMutationData>
} {
  return {
    mutationKey: mutationKeySubscribersPreferencesUpdate(),
    mutationFn: function subscribersPreferencesUpdateMutationFn({
      patchSubscriberPreferencesDto,
      subscriberId,
      idempotencyKey,
      options,
    }): Promise<SubscribersPreferencesUpdateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        subscribersPreferencesUpdate(
          client$,
          patchSubscriberPreferencesDto,
          subscriberId,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
