/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { subscribersMessagesMarkAll } from "../funcs/subscribersMessagesMarkAll.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type SubscribersMessagesMarkAllMutationVariables = {
  markAllMessageAsRequestDto: components.MarkAllMessageAsRequestDto
  subscriberId: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type SubscribersMessagesMarkAllMutationData =
  operations.SubscribersV1ControllerMarkAllUnreadAsReadResponse

export type SubscribersMessagesMarkAllMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Update all notifications state
 *
 * @remarks
 * Update all subscriber in-app (inbox) notifications state such as read, unread, seen or unseen by **subscriberId**.
 */
export function useSubscribersMessagesMarkAllMutation(
  options?: MutationHookOptions<
    SubscribersMessagesMarkAllMutationData,
    SubscribersMessagesMarkAllMutationError,
    SubscribersMessagesMarkAllMutationVariables
  >
): UseMutationResult<
  SubscribersMessagesMarkAllMutationData,
  SubscribersMessagesMarkAllMutationError,
  SubscribersMessagesMarkAllMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildSubscribersMessagesMarkAllMutation(client, options),
    ...options,
  })
}

export function mutationKeySubscribersMessagesMarkAll(): MutationKey {
  return ["@novu/api", "Messages", "markAll"]
}

export function buildSubscribersMessagesMarkAllMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: SubscribersMessagesMarkAllMutationVariables
  ) => Promise<SubscribersMessagesMarkAllMutationData>
} {
  return {
    mutationKey: mutationKeySubscribersMessagesMarkAll(),
    mutationFn: function subscribersMessagesMarkAllMutationFn({
      markAllMessageAsRequestDto,
      subscriberId,
      idempotencyKey,
      options,
    }): Promise<SubscribersMessagesMarkAllMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        subscribersMessagesMarkAll(
          client$,
          markAllMessageAsRequestDto,
          subscriberId,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
