/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { subscribersPropertiesUpdateOnlineFlag } from "../funcs/subscribersPropertiesUpdateOnlineFlag.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type SubscribersPropertiesUpdateOnlineFlagMutationVariables = {
  updateSubscriberOnlineFlagRequestDto: components.UpdateSubscriberOnlineFlagRequestDto
  subscriberId: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type SubscribersPropertiesUpdateOnlineFlagMutationData =
  operations.SubscribersV1ControllerUpdateSubscriberOnlineFlagResponse

export type SubscribersPropertiesUpdateOnlineFlagMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Update subscriber online status
 *
 * @remarks
 * Update the subscriber online status by its unique key identifier **subscriberId**
 */
export function useSubscribersPropertiesUpdateOnlineFlagMutation(
  options?: MutationHookOptions<
    SubscribersPropertiesUpdateOnlineFlagMutationData,
    SubscribersPropertiesUpdateOnlineFlagMutationError,
    SubscribersPropertiesUpdateOnlineFlagMutationVariables
  >
): UseMutationResult<
  SubscribersPropertiesUpdateOnlineFlagMutationData,
  SubscribersPropertiesUpdateOnlineFlagMutationError,
  SubscribersPropertiesUpdateOnlineFlagMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildSubscribersPropertiesUpdateOnlineFlagMutation(client, options),
    ...options,
  })
}

export function mutationKeySubscribersPropertiesUpdateOnlineFlag(): MutationKey {
  return ["@novu/api", "properties", "updateOnlineFlag"]
}

export function buildSubscribersPropertiesUpdateOnlineFlagMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: SubscribersPropertiesUpdateOnlineFlagMutationVariables
  ) => Promise<SubscribersPropertiesUpdateOnlineFlagMutationData>
} {
  return {
    mutationKey: mutationKeySubscribersPropertiesUpdateOnlineFlag(),
    mutationFn: function subscribersPropertiesUpdateOnlineFlagMutationFn({
      updateSubscriberOnlineFlagRequestDto,
      subscriberId,
      idempotencyKey,
      options,
    }): Promise<SubscribersPropertiesUpdateOnlineFlagMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        subscribersPropertiesUpdateOnlineFlag(
          client$,
          updateSubscriberOnlineFlagRequestDto,
          subscriberId,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
