/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { subscribersNotificationsArchive } from "../funcs/subscribersNotificationsArchive.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type SubscribersNotificationsArchiveMutationVariables = {
  request: operations.SubscribersControllerArchiveNotificationRequest
  options?: RequestOptions
}

export type SubscribersNotificationsArchiveMutationData =
  operations.SubscribersControllerArchiveNotificationResponse

export type SubscribersNotificationsArchiveMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Archive a notification
 *
 * @remarks
 * Archive a specific in-app (inbox) notification by its unique identifier **notificationId**.
 */
export function useSubscribersNotificationsArchiveMutation(
  options?: MutationHookOptions<
    SubscribersNotificationsArchiveMutationData,
    SubscribersNotificationsArchiveMutationError,
    SubscribersNotificationsArchiveMutationVariables
  >
): UseMutationResult<
  SubscribersNotificationsArchiveMutationData,
  SubscribersNotificationsArchiveMutationError,
  SubscribersNotificationsArchiveMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildSubscribersNotificationsArchiveMutation(client, options),
    ...options,
  })
}

export function mutationKeySubscribersNotificationsArchive(): MutationKey {
  return ["@novu/api", "Notifications", "archive"]
}

export function buildSubscribersNotificationsArchiveMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: SubscribersNotificationsArchiveMutationVariables
  ) => Promise<SubscribersNotificationsArchiveMutationData>
} {
  return {
    mutationKey: mutationKeySubscribersNotificationsArchive(),
    mutationFn: function subscribersNotificationsArchiveMutationFn({
      request,
      options,
    }): Promise<SubscribersNotificationsArchiveMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        subscribersNotificationsArchive(client$, request, mergedOptions)
      )
    },
  }
}
