/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { subscribersNotificationsMarkAllAsRead } from "../funcs/subscribersNotificationsMarkAllAsRead.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type SubscribersNotificationsMarkAllAsReadMutationVariables = {
  updateAllSubscriberNotificationsDto: components.UpdateAllSubscriberNotificationsDto
  subscriberId: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type SubscribersNotificationsMarkAllAsReadMutationData =
  | operations.SubscribersControllerMarkAllNotificationsAsReadResponse
  | undefined

export type SubscribersNotificationsMarkAllAsReadMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Mark all notifications as read
 *
 * @remarks
 * Mark all in-app (inbox) notifications matching the specified filters as read. Supports context-based filtering.
 */
export function useSubscribersNotificationsMarkAllAsReadMutation(
  options?: MutationHookOptions<
    SubscribersNotificationsMarkAllAsReadMutationData,
    SubscribersNotificationsMarkAllAsReadMutationError,
    SubscribersNotificationsMarkAllAsReadMutationVariables
  >
): UseMutationResult<
  SubscribersNotificationsMarkAllAsReadMutationData,
  SubscribersNotificationsMarkAllAsReadMutationError,
  SubscribersNotificationsMarkAllAsReadMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildSubscribersNotificationsMarkAllAsReadMutation(client, options),
    ...options,
  })
}

export function mutationKeySubscribersNotificationsMarkAllAsRead(): MutationKey {
  return ["@novu/api", "Notifications", "markAllAsRead"]
}

export function buildSubscribersNotificationsMarkAllAsReadMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: SubscribersNotificationsMarkAllAsReadMutationVariables
  ) => Promise<SubscribersNotificationsMarkAllAsReadMutationData>
} {
  return {
    mutationKey: mutationKeySubscribersNotificationsMarkAllAsRead(),
    mutationFn: function subscribersNotificationsMarkAllAsReadMutationFn({
      updateAllSubscriberNotificationsDto,
      subscriberId,
      idempotencyKey,
      options,
    }): Promise<SubscribersNotificationsMarkAllAsReadMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        subscribersNotificationsMarkAllAsRead(
          client$,
          updateAllSubscriberNotificationsDto,
          subscriberId,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
