/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { subscribersNotificationsDeleteAll } from "../funcs/subscribersNotificationsDeleteAll.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type SubscribersNotificationsDeleteAllMutationVariables = {
  updateAllSubscriberNotificationsDto: components.UpdateAllSubscriberNotificationsDto
  subscriberId: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type SubscribersNotificationsDeleteAllMutationData =
  | operations.SubscribersControllerDeleteAllNotificationsResponse
  | undefined

export type SubscribersNotificationsDeleteAllMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Delete all notifications
 *
 * @remarks
 * Permanently delete all in-app (inbox) notifications matching the specified filters. Supports context-based filtering.
 */
export function useSubscribersNotificationsDeleteAllMutation(
  options?: MutationHookOptions<
    SubscribersNotificationsDeleteAllMutationData,
    SubscribersNotificationsDeleteAllMutationError,
    SubscribersNotificationsDeleteAllMutationVariables
  >
): UseMutationResult<
  SubscribersNotificationsDeleteAllMutationData,
  SubscribersNotificationsDeleteAllMutationError,
  SubscribersNotificationsDeleteAllMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildSubscribersNotificationsDeleteAllMutation(client, options),
    ...options,
  })
}

export function mutationKeySubscribersNotificationsDeleteAll(): MutationKey {
  return ["@novu/api", "Notifications", "deleteAll"]
}

export function buildSubscribersNotificationsDeleteAllMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: SubscribersNotificationsDeleteAllMutationVariables
  ) => Promise<SubscribersNotificationsDeleteAllMutationData>
} {
  return {
    mutationKey: mutationKeySubscribersNotificationsDeleteAll(),
    mutationFn: function subscribersNotificationsDeleteAllMutationFn({
      updateAllSubscriberNotificationsDto,
      subscriberId,
      idempotencyKey,
      options,
    }): Promise<SubscribersNotificationsDeleteAllMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        subscribersNotificationsDeleteAll(
          client$,
          updateAllSubscriberNotificationsDto,
          subscriberId,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
