/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { topicsCreate } from "../funcs/topicsCreate.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type TopicsCreateMutationVariables = {
  createUpdateTopicRequestDto: components.CreateUpdateTopicRequestDto
  failIfExists?: boolean | undefined
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type TopicsCreateMutationData =
  operations.TopicsControllerUpsertTopicResponse

export type TopicsCreateMutationError =
  | errors.TopicResponseDto
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Create a topic
 *
 * @remarks
 * Creates a new topic if it does not exist, or updates an existing topic if it already exists. Use ?failIfExists=true to prevent updates.
 */
export function useTopicsCreateMutation(
  options?: MutationHookOptions<
    TopicsCreateMutationData,
    TopicsCreateMutationError,
    TopicsCreateMutationVariables
  >
): UseMutationResult<
  TopicsCreateMutationData,
  TopicsCreateMutationError,
  TopicsCreateMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildTopicsCreateMutation(client, options),
    ...options,
  })
}

export function mutationKeyTopicsCreate(): MutationKey {
  return ["@novu/api", "Topics", "create"]
}

export function buildTopicsCreateMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: TopicsCreateMutationVariables
  ) => Promise<TopicsCreateMutationData>
} {
  return {
    mutationKey: mutationKeyTopicsCreate(),
    mutationFn: function topicsCreateMutationFn({
      createUpdateTopicRequestDto,
      failIfExists,
      idempotencyKey,
      options,
    }): Promise<TopicsCreateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        topicsCreate(
          client$,
          createUpdateTopicRequestDto,
          failIfExists,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
