/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { translationsDelete } from "../funcs/translationsDelete.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type TranslationsDeleteMutationVariables = {
  request: operations.TranslationControllerDeleteTranslationEndpointRequest
  options?: RequestOptions
}

export type TranslationsDeleteMutationData = void

export type TranslationsDeleteMutationError =
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Delete a translation
 *
 * @remarks
 * Delete a specific translation by resource type, resource ID and locale
 */
export function useTranslationsDeleteMutation(
  options?: MutationHookOptions<
    TranslationsDeleteMutationData,
    TranslationsDeleteMutationError,
    TranslationsDeleteMutationVariables
  >
): UseMutationResult<
  TranslationsDeleteMutationData,
  TranslationsDeleteMutationError,
  TranslationsDeleteMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildTranslationsDeleteMutation(client, options),
    ...options,
  })
}

export function mutationKeyTranslationsDelete(): MutationKey {
  return ["@novu/api", "Translations", "delete"]
}

export function buildTranslationsDeleteMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: TranslationsDeleteMutationVariables
  ) => Promise<TranslationsDeleteMutationData>
} {
  return {
    mutationKey: mutationKeyTranslationsDelete(),
    mutationFn: function translationsDeleteMutationFn({
      request,
      options,
    }): Promise<TranslationsDeleteMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(translationsDelete(client$, request, mergedOptions))
    },
  }
}
