/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { translationsGroupsDelete } from "../funcs/translationsGroupsDelete.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type TranslationsGroupsDeleteMutationVariables = {
  resourceType: operations.TranslationControllerDeleteTranslationGroupEndpointPathParamResourceType
  resourceId: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type TranslationsGroupsDeleteMutationData = void

export type TranslationsGroupsDeleteMutationError =
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Delete a translation group
 *
 * @remarks
 * Delete an entire translation group and all its translations
 */
export function useTranslationsGroupsDeleteMutation(
  options?: MutationHookOptions<
    TranslationsGroupsDeleteMutationData,
    TranslationsGroupsDeleteMutationError,
    TranslationsGroupsDeleteMutationVariables
  >
): UseMutationResult<
  TranslationsGroupsDeleteMutationData,
  TranslationsGroupsDeleteMutationError,
  TranslationsGroupsDeleteMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildTranslationsGroupsDeleteMutation(client, options),
    ...options,
  })
}

export function mutationKeyTranslationsGroupsDelete(): MutationKey {
  return ["@novu/api", "Groups", "delete"]
}

export function buildTranslationsGroupsDeleteMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: TranslationsGroupsDeleteMutationVariables
  ) => Promise<TranslationsGroupsDeleteMutationData>
} {
  return {
    mutationKey: mutationKeyTranslationsGroupsDelete(),
    mutationFn: function translationsGroupsDeleteMutationFn({
      resourceType,
      resourceId,
      idempotencyKey,
      options,
    }): Promise<TranslationsGroupsDeleteMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        translationsGroupsDelete(
          client$,
          resourceType,
          resourceId,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
