/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { translationsMasterUpload } from "../funcs/translationsMasterUpload.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type TranslationsMasterUploadMutationVariables = {
  requestBody: operations.TranslationControllerUploadMasterJsonEndpointRequestBody
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type TranslationsMasterUploadMutationData =
  components.ImportMasterJsonResponseDto

export type TranslationsMasterUploadMutationError =
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Upload master translations JSON file
 *
 * @remarks
 * Upload a master JSON file containing translations for multiple workflows. Locale is automatically detected from filename (e.g., en_US.json)
 */
export function useTranslationsMasterUploadMutation(
  options?: MutationHookOptions<
    TranslationsMasterUploadMutationData,
    TranslationsMasterUploadMutationError,
    TranslationsMasterUploadMutationVariables
  >
): UseMutationResult<
  TranslationsMasterUploadMutationData,
  TranslationsMasterUploadMutationError,
  TranslationsMasterUploadMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildTranslationsMasterUploadMutation(client, options),
    ...options,
  })
}

export function mutationKeyTranslationsMasterUpload(): MutationKey {
  return ["@novu/api", "master", "upload"]
}

export function buildTranslationsMasterUploadMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: TranslationsMasterUploadMutationVariables
  ) => Promise<TranslationsMasterUploadMutationData>
} {
  return {
    mutationKey: mutationKeyTranslationsMasterUpload(),
    mutationFn: function translationsMasterUploadMutationFn({
      requestBody,
      idempotencyKey,
      options,
    }): Promise<TranslationsMasterUploadMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        translationsMasterUpload(
          client$,
          requestBody,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
