/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { trigger } from "../funcs/trigger.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type TriggerMutationVariables = {
  triggerEventRequestDto: components.TriggerEventRequestDto
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type TriggerMutationData = operations.EventsControllerTriggerResponse

export type TriggerMutationError =
  | errors.PayloadValidationExceptionDto
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Trigger event
 *
 * @remarks
 *
 *     Trigger event is the main (and only) way to send notifications to subscribers. The trigger identifier is used to match the particular workflow associated with it. Maximum number of recipients can be 100. Additional information can be passed according the body interface below.
 *     To prevent duplicate triggers, you can optionally pass a **transactionId** in the request body. If the same **transactionId** is used again, the trigger will be ignored. The retention period depends on your billing tier.
 */
export function useTriggerMutation(
  options?: MutationHookOptions<
    TriggerMutationData,
    TriggerMutationError,
    TriggerMutationVariables
  >
): UseMutationResult<
  TriggerMutationData,
  TriggerMutationError,
  TriggerMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildTriggerMutation(client, options),
    ...options,
  })
}

export function mutationKeyTrigger(): MutationKey {
  return ["@novu/api", "trigger"]
}

export function buildTriggerMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: TriggerMutationVariables
  ) => Promise<TriggerMutationData>
} {
  return {
    mutationKey: mutationKeyTrigger(),
    mutationFn: function triggerMutationFn({
      triggerEventRequestDto,
      idempotencyKey,
      options,
    }): Promise<TriggerMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        trigger(client$, triggerEventRequestDto, idempotencyKey, mergedOptions)
      )
    },
  }
}
