/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { triggerBulk } from "../funcs/triggerBulk.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type TriggerBulkMutationVariables = {
  bulkTriggerEventDto: components.BulkTriggerEventDto
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type TriggerBulkMutationData =
  operations.EventsControllerTriggerBulkResponse

export type TriggerBulkMutationError =
  | errors.PayloadValidationExceptionDto
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Bulk trigger event
 *
 * @remarks
 *
 *       Using this endpoint you can trigger multiple events at once, to avoid multiple calls to the API.
 *       The bulk API is limited to 100 events per request.
 */
export function useTriggerBulkMutation(
  options?: MutationHookOptions<
    TriggerBulkMutationData,
    TriggerBulkMutationError,
    TriggerBulkMutationVariables
  >
): UseMutationResult<
  TriggerBulkMutationData,
  TriggerBulkMutationError,
  TriggerBulkMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildTriggerBulkMutation(client, options),
    ...options,
  })
}

export function mutationKeyTriggerBulk(): MutationKey {
  return ["@novu/api", "triggerBulk"]
}

export function buildTriggerBulkMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: TriggerBulkMutationVariables
  ) => Promise<TriggerBulkMutationData>
} {
  return {
    mutationKey: mutationKeyTriggerBulk(),
    mutationFn: function triggerBulkMutationFn({
      bulkTriggerEventDto,
      idempotencyKey,
      options,
    }): Promise<TriggerBulkMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        triggerBulk(client$, bulkTriggerEventDto, idempotencyKey, mergedOptions)
      )
    },
  }
}
