/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { triggerBroadcast } from "../funcs/triggerBroadcast.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type TriggerBroadcastMutationVariables = {
  triggerEventToAllRequestDto: components.TriggerEventToAllRequestDto
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type TriggerBroadcastMutationData =
  operations.EventsControllerBroadcastEventToAllResponse

export type TriggerBroadcastMutationError =
  | errors.PayloadValidationExceptionDto
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Broadcast event to all
 *
 * @remarks
 * Trigger a broadcast event to all existing subscribers, could be used to send announcements, etc.
 *       In the future could be used to trigger events to a subset of subscribers based on defined filters.
 */
export function useTriggerBroadcastMutation(
  options?: MutationHookOptions<
    TriggerBroadcastMutationData,
    TriggerBroadcastMutationError,
    TriggerBroadcastMutationVariables
  >
): UseMutationResult<
  TriggerBroadcastMutationData,
  TriggerBroadcastMutationError,
  TriggerBroadcastMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildTriggerBroadcastMutation(client, options),
    ...options,
  })
}

export function mutationKeyTriggerBroadcast(): MutationKey {
  return ["@novu/api", "triggerBroadcast"]
}

export function buildTriggerBroadcastMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: TriggerBroadcastMutationVariables
  ) => Promise<TriggerBroadcastMutationData>
} {
  return {
    mutationKey: mutationKeyTriggerBroadcast(),
    mutationFn: function triggerBroadcastMutationFn({
      triggerEventToAllRequestDto,
      idempotencyKey,
      options,
    }): Promise<TriggerBroadcastMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        triggerBroadcast(
          client$,
          triggerEventToAllRequestDto,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
