/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { workflowsUpdate } from "../funcs/workflowsUpdate.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type WorkflowsUpdateMutationVariables = {
  updateWorkflowDto: components.UpdateWorkflowDto
  workflowId: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type WorkflowsUpdateMutationData =
  operations.WorkflowControllerUpdateResponse

export type WorkflowsUpdateMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Update a workflow
 *
 * @remarks
 * Updates the details of an existing workflow, here **workflowId** is the identifier of the workflow
 */
export function useWorkflowsUpdateMutation(
  options?: MutationHookOptions<
    WorkflowsUpdateMutationData,
    WorkflowsUpdateMutationError,
    WorkflowsUpdateMutationVariables
  >
): UseMutationResult<
  WorkflowsUpdateMutationData,
  WorkflowsUpdateMutationError,
  WorkflowsUpdateMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildWorkflowsUpdateMutation(client, options),
    ...options,
  })
}

export function mutationKeyWorkflowsUpdate(): MutationKey {
  return ["@novu/api", "Workflows", "update"]
}

export function buildWorkflowsUpdateMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: WorkflowsUpdateMutationVariables
  ) => Promise<WorkflowsUpdateMutationData>
} {
  return {
    mutationKey: mutationKeyWorkflowsUpdate(),
    mutationFn: function workflowsUpdateMutationFn({
      updateWorkflowDto,
      workflowId,
      idempotencyKey,
      options,
    }): Promise<WorkflowsUpdateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        workflowsUpdate(
          client$,
          updateWorkflowDto,
          workflowId,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
