/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  type MutationKey,
  type UseMutationResult,
  useMutation,
} from "@tanstack/react-query"
import type { NovuCore } from "../core.js"
import { workflowsSync } from "../funcs/workflowsSync.js"
import { combineSignals } from "../lib/primitives.js"
import type { RequestOptions } from "../lib/sdks.js"
import type * as components from "../models/components/index.js"
import type {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js"
import type * as errors from "../models/errors/index.js"
import type { NovuError } from "../models/errors/novuerror.js"
import type { ResponseValidationError } from "../models/errors/responsevalidationerror.js"
import type { SDKValidationError } from "../models/errors/sdkvalidationerror.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"
import { useNovuContext } from "./_context.js"
import type { MutationHookOptions } from "./_types.js"

export type WorkflowsSyncMutationVariables = {
  syncWorkflowDto: components.SyncWorkflowDto
  workflowId: string
  idempotencyKey?: string | undefined
  options?: RequestOptions
}

export type WorkflowsSyncMutationData =
  operations.WorkflowControllerSyncResponse

export type WorkflowsSyncMutationError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError

/**
 * Sync a workflow
 *
 * @remarks
 * Synchronizes a workflow to the target environment
 */
export function useWorkflowsSyncMutation(
  options?: MutationHookOptions<
    WorkflowsSyncMutationData,
    WorkflowsSyncMutationError,
    WorkflowsSyncMutationVariables
  >
): UseMutationResult<
  WorkflowsSyncMutationData,
  WorkflowsSyncMutationError,
  WorkflowsSyncMutationVariables
> {
  const client = useNovuContext()
  return useMutation({
    ...buildWorkflowsSyncMutation(client, options),
    ...options,
  })
}

export function mutationKeyWorkflowsSync(): MutationKey {
  return ["@novu/api", "Workflows", "sync"]
}

export function buildWorkflowsSyncMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey
  mutationFn: (
    variables: WorkflowsSyncMutationVariables
  ) => Promise<WorkflowsSyncMutationData>
} {
  return {
    mutationKey: mutationKeyWorkflowsSync(),
    mutationFn: function workflowsSyncMutationFn({
      syncWorkflowDto,
      workflowId,
      idempotencyKey,
      options,
    }): Promise<WorkflowsSyncMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal
          ),
        },
      }
      return unwrapAsync(
        workflowsSync(
          client$,
          syncWorkflowDto,
          workflowId,
          idempotencyKey,
          mergedOptions
        )
      )
    },
  }
}
