/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3"
import { safeParse } from "../../lib/schemas.js"
import type { Result as SafeParseResult } from "../../types/fp.js"
import type { SDKValidationError } from "../errors/sdkvalidationerror.js"
import { type MetaDto, MetaDto$inboundSchema } from "./metadto.js"
import {
  type SubscriptionErrorDto,
  SubscriptionErrorDto$inboundSchema,
} from "./subscriptionerrordto.js"
import {
  type SubscriptionResponseDto,
  SubscriptionResponseDto$inboundSchema,
} from "./subscriptionresponsedto.js"

export type CreateSubscriptionsResponseDto = {
  /**
   * The list of successfully created subscriptions
   */
  data: Array<SubscriptionResponseDto>
  /**
   * Metadata about the operation
   */
  meta: MetaDto
  /**
   * The list of errors for failed subscription attempts
   */
  errors?: Array<SubscriptionErrorDto> | undefined
}

/** @internal */
export const CreateSubscriptionsResponseDto$inboundSchema: z.ZodType<
  CreateSubscriptionsResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(SubscriptionResponseDto$inboundSchema),
  meta: MetaDto$inboundSchema,
  errors: z.array(SubscriptionErrorDto$inboundSchema).optional(),
})

export function createSubscriptionsResponseDtoFromJSON(
  jsonString: string
): SafeParseResult<CreateSubscriptionsResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateSubscriptionsResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateSubscriptionsResponseDto' from JSON`
  )
}
