/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3"
import { safeParse } from "../../lib/schemas.js"
import type { Result as SafeParseResult } from "../../types/fp.js"
import type { SDKValidationError } from "../errors/sdkvalidationerror.js"
import {
  type DigestControlDto,
  DigestControlDto$inboundSchema,
} from "./digestcontroldto.js"
import { type UiSchema, UiSchema$inboundSchema } from "./uischema.js"

export type DigestControlsMetadataResponseDto = {
  /**
   * JSON Schema for data
   */
  dataSchema?: { [k: string]: any } | undefined
  /**
   * UI Schema for rendering
   */
  uiSchema?: UiSchema | undefined
  /**
   * Control values specific to Digest
   */
  values: DigestControlDto
}

/** @internal */
export const DigestControlsMetadataResponseDto$inboundSchema: z.ZodType<
  DigestControlsMetadataResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  dataSchema: z.record(z.any()).optional(),
  uiSchema: UiSchema$inboundSchema.optional(),
  values: DigestControlDto$inboundSchema,
})

export function digestControlsMetadataResponseDtoFromJSON(
  jsonString: string
): SafeParseResult<DigestControlsMetadataResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DigestControlsMetadataResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DigestControlsMetadataResponseDto' from JSON`
  )
}
