/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3"
import { remap as remap$ } from "../../lib/primitives.js"
import { safeParse } from "../../lib/schemas.js"
import type { ClosedEnum } from "../../types/enums.js"
import type { Result as SafeParseResult } from "../../types/fp.js"
import type { SDKValidationError } from "../errors/sdkvalidationerror.js"
import {
  type ExpectedDnsRecordDto,
  ExpectedDnsRecordDto$inboundSchema,
} from "./expecteddnsrecorddto.js"

export const DomainResponseDtoStatus = {
  Pending: "pending",
  Verified: "verified",
} as const
export type DomainResponseDtoStatus = ClosedEnum<typeof DomainResponseDtoStatus>

export type DomainResponseDto = {
  id: string
  name: string
  status: DomainResponseDtoStatus
  mxRecordConfigured: boolean
  dnsProvider?: string | undefined
  environmentId: string
  organizationId: string
  createdAt: string
  updatedAt: string
  expectedDnsRecords?: Array<ExpectedDnsRecordDto> | undefined
  /**
   * String key-value metadata (max 10 keys, 500 characters total when set via API).
   */
  data?: { [k: string]: string } | undefined
}

/** @internal */
export const DomainResponseDtoStatus$inboundSchema: z.ZodNativeEnum<
  typeof DomainResponseDtoStatus
> = z.nativeEnum(DomainResponseDtoStatus)

/** @internal */
export const DomainResponseDto$inboundSchema: z.ZodType<
  DomainResponseDto,
  z.ZodTypeDef,
  unknown
> = z
  .object({
    _id: z.string(),
    name: z.string(),
    status: DomainResponseDtoStatus$inboundSchema,
    mxRecordConfigured: z.boolean(),
    dnsProvider: z.string().optional(),
    _environmentId: z.string(),
    _organizationId: z.string(),
    createdAt: z.string(),
    updatedAt: z.string(),
    expectedDnsRecords: z.array(ExpectedDnsRecordDto$inboundSchema).optional(),
    data: z.record(z.string()).optional(),
  })
  .transform((v) => {
    return remap$(v, {
      _id: "id",
      _environmentId: "environmentId",
      _organizationId: "organizationId",
    })
  })

export function domainResponseDtoFromJSON(
  jsonString: string
): SafeParseResult<DomainResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DomainResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DomainResponseDto' from JSON`
  )
}
