/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3"
import { safeParse } from "../../lib/schemas.js"
import type { ClosedEnum } from "../../types/enums.js"
import type { Result as SafeParseResult } from "../../types/fp.js"
import type { SDKValidationError } from "../errors/sdkvalidationerror.js"
import {
  type ExpectedDnsRecordDto,
  ExpectedDnsRecordDto$inboundSchema,
} from "./expecteddnsrecorddto.js"

export const ReasonCode = {
  Disabled: "disabled",
  DiscoveryNotConfigured: "discovery_not_configured",
  UnsupportedProvider: "unsupported_provider",
  IncompleteConfiguration: "incomplete_configuration",
  ProviderSettingsUnavailable: "provider_settings_unavailable",
  UntrustedProviderFlow: "untrusted_provider_flow",
  TemplateNotOnboarded: "template_not_onboarded",
} as const
export type ReasonCode = ClosedEnum<typeof ReasonCode>

export type DomainConnectStatusResponseDto = {
  available: boolean
  providerName?: string | undefined
  providerId?: string | undefined
  reason?: string | undefined
  reasonCode?: ReasonCode | undefined
  manualRecords: Array<ExpectedDnsRecordDto>
}

/** @internal */
export const ReasonCode$inboundSchema: z.ZodNativeEnum<typeof ReasonCode> =
  z.nativeEnum(ReasonCode)

/** @internal */
export const DomainConnectStatusResponseDto$inboundSchema: z.ZodType<
  DomainConnectStatusResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  available: z.boolean(),
  providerName: z.string().optional(),
  providerId: z.string().optional(),
  reason: z.string().optional(),
  reasonCode: ReasonCode$inboundSchema.optional(),
  manualRecords: z.array(ExpectedDnsRecordDto$inboundSchema),
})

export function domainConnectStatusResponseDtoFromJSON(
  jsonString: string
): SafeParseResult<DomainConnectStatusResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DomainConnectStatusResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DomainConnectStatusResponseDto' from JSON`
  )
}
