/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3"
import { safeParse } from "../../lib/schemas.js"
import type { Result as SafeParseResult } from "../../types/fp.js"
import type { SDKValidationError } from "../errors/sdkvalidationerror.js"
import {
  type WorkflowInfoDto,
  WorkflowInfoDto$inboundSchema,
} from "./workflowinfodto.js"

export type GetLayoutUsageResponseDto = {
  /**
   * Array of workflows that use this layout
   */
  workflows: Array<WorkflowInfoDto>
}

/** @internal */
export const GetLayoutUsageResponseDto$inboundSchema: z.ZodType<
  GetLayoutUsageResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  workflows: z.array(WorkflowInfoDto$inboundSchema),
})

export function getLayoutUsageResponseDtoFromJSON(
  jsonString: string
): SafeParseResult<GetLayoutUsageResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetLayoutUsageResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetLayoutUsageResponseDto' from JSON`
  )
}
