/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3"
import { safeParse } from "../../lib/schemas.js"
import type { Result as SafeParseResult } from "../../types/fp.js"
import type { SDKValidationError } from "../errors/sdkvalidationerror.js"
import {
  type ChannelTypeEnum,
  ChannelTypeEnum$inboundSchema,
} from "./channeltypeenum.js"
import {
  type PreferenceOverrideSourceEnum,
  PreferenceOverrideSourceEnum$inboundSchema,
} from "./preferenceoverridesourceenum.js"

export type SubscriberPreferenceOverrideDto = {
  /**
   * Channel type through which the message is sent
   */
  channel: ChannelTypeEnum
  /**
   * The source of overrides
   */
  source: PreferenceOverrideSourceEnum
}

/** @internal */
export const SubscriberPreferenceOverrideDto$inboundSchema: z.ZodType<
  SubscriberPreferenceOverrideDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  channel: ChannelTypeEnum$inboundSchema,
  source: PreferenceOverrideSourceEnum$inboundSchema,
})

export function subscriberPreferenceOverrideDtoFromJSON(
  jsonString: string
): SafeParseResult<SubscriberPreferenceOverrideDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SubscriberPreferenceOverrideDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubscriberPreferenceOverrideDto' from JSON`
  )
}
